### ISSUE TITLE
Implementing the PlaceHolder Content Control

### ISSUE THREAD

**Issue by IsYet1** [SharePoint/sp-dev-fx-controls-react#1]
[ ] Enhancement

[ ] Bug

[ X ] Question

#### Version
spfx-controls-react@1.0.0-beta.6

#### Question - Easier way to implement the Place Holder control?
I'm new to React and to SPFx. :-) 
_The relevant files are attached in a .zip_

**Primary questions**
- Best place to put the <Placeholder markup code
- Best way to get the context to get at the propertyPane

I was able to get the PlaceHolder content control to work but I'm wondering if there's a better way.

My project is called **React00** so this is the prefix for all the files.

I put the <Placeholder markup in the **React00.tsx** file (attached) that has the default React Welcome code.

I got the context from the **React00WebPart.ts**.
To do that, I used code from a previous project that uses the pnp object in the sp-pnp-js package. _After installing the package._
To get it from the WebPart to the React file, I added a WebPartContext property to the IReact00Props.ts interface.

This all works as expected but I'm curious if there's a simpler route.

Thanks!

[PlaceHolderSPFxCode.zip](https://github.com/SharePoint/sp-dev-fx-controls-react/files/1360541/PlaceHolderSPFxCode.zip)

**Comment by estruyf** [comment]
Did not have the time yet to check it, but have you already tested the sample web part? You can find it here: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/pnp-controls

**Comment by IsYet1** [comment]
Thanks! I'll definitely take a look at these samples.
I should have mentioned, for clarity, that web part I'm working with was created with the SharePoint generator - React framework.

**Comment by IsYet1** [comment]
My code was close. I over-complicated getting the context.
Thanks.
