### ISSUE TITLE
An odd error when using the ListView Control

### ISSUE THREAD

**Issue by Katli95** [SharePoint/sp-dev-fx-controls-react#106]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Expected / Desired Behavior / Question
I expected a simple list item to be rendered

![image](https://user-images.githubusercontent.com/11443825/43736103-05210662-99ac-11e8-9a22-64128ad65e9e.png)

#### Observed Behavior
I'm getting an obscure React error (on their website because I don't quite know how to run the dev build and the callstack is just full of sp-webpart-workbench... calls):

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of 'DetailsColumn'`

#### Steps to Reproduce
Just try to render a simple item in a listview.

Any ideas as to what might be causing this issue? 
It is only present when I try to render the ListView component, other simple components work :/

Thanks!

**Comment by Katli95** [comment]
I believe this is happening because of an update to the [`<DetailsColumn/>`](https://github.com/laxmikankanala/office-ui-fabric-react/blob/019dbf740f3cb75f8a9b8eaa13bbef20c2a37184/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.tsx) component used by `<DetailsList/>` which is of course a central part to this `<ListView/>` control. 

If we look at the `.render()` method of DetailsColumn we see it is rendering the component using reacts new [Fraction Short Hand syntax](https://reactjs.org/docs/fragments.html#short-syntax) which I believe is introduced in react 16.2. 

Could this then be caused by `SPFx` and `sp-dev-fx-controls-react` having a dependency lower than that of `office-ui-fabric-react`, 15.6.2 and 16.3.16 respectively?

I'm still relatively new to the web development scene, especially regarding all these different versions and their interactions. Any ideas as to what I might do to solve this problem?

Any and all recommendations welcome!

**Comment by estruyf** [comment]
Just tested this with version `1.6.0` in combination with a SPFx `1.5.1` project and it runs without any issues. 

Have you manually installed a new version of Office UI Fabric React in your project? 

![screenshot 2018-08-09 18 00 52](https://user-images.githubusercontent.com/2900833/43910869-4888b8ba-9bfe-11e8-921f-d1e7dce07cae.png)

![listview-issue](https://user-images.githubusercontent.com/2900833/43910878-4b783a6e-9bfe-11e8-84aa-b5cf3c74ad0d.png)

**Comment by Katli95** [comment]
Yeah, I had installed it to use e.g. the spinner, turns out that reverting to an older version of fabric eliminated this error. Does this happen because npm packages use the most recent locally available copy of a dependency? My knowledge of packages is lacking in this regard, I haven't really found a good resource explaining the interplay between various dependencies.
