### ISSUE TITLE
Taxonomy Picker panel including terms that are depreciated / unavailable for tagging

### ISSUE THREAD

**Issue by bealsao** [SharePoint/sp-dev-fx-controls-react#109]
#### Category
[ ] Enhancement
[X] Bug
[ ] Question

#### Version
Please specify what version of the library you are using: [v1.7.0]

#### Expected / Desired Behavior / Question
Terms that are depreciated / unavailable for tagging should not be available in the callout panel.

#### Observed Behavior
This behavior is working when using the auto-complete search box but not when using the callout panel.

#### Steps to Reproduce
Depreciate / make a term unavailable for tagging:
![image](https://user-images.githubusercontent.com/36017121/44127794-5433c7a8-a082-11e8-902e-a2b7ca459131.png)

Then attempt to find the term using the search box and the search box will not return the item:
![image](https://user-images.githubusercontent.com/36017121/44127649-a9df3422-a081-11e8-89e6-4bcbad42e371.png)
![image](https://user-images.githubusercontent.com/36017121/44127686-d31ebf92-a081-11e8-9de0-20fe67231d22.png)

When clicking the callout panel it will provide the option to tag both terms:
![image](https://user-images.githubusercontent.com/36017121/44127702-ef8e355e-a081-11e8-8da9-39bf809b1ad4.png)
![image](https://user-images.githubusercontent.com/36017121/44127704-f54e341c-a081-11e8-9ba3-8ae16fb99544.png)

**Comment by estruyf** [comment]
Thanks @bealsao for reporting this, I have worked on a fix and this one will be included in version `1.8.0`.

If you want, you can already test out the beta version. More information about this: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by bealsao** [comment]
@estruyf  Thank you!

**Comment by bealsao** [comment]
Accident sorry!
