### ISSUE TITLE
ListView selection executes twice, both badly

### ISSUE THREAD

**Issue by kmosti** [SharePoint/sp-dev-fx-controls-react#11]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

1.0.0-beta.6

#### Expected / Desired Behavior / Question
I have a ListView component that is set like this:

```
<ListView
          items={this.state.reactListItems}
          compact={true}
          viewFields={viewFields}
          selectionMode={SelectionMode.single}
          selection={ (e) => this.setState({
            showPanel: true,
            panelInfo: JSON.stringify(e)
          })} />
```

In the selection area I have set a state update using local fat arrow to pass the _this_ object, which I want to use in a panel (or modal or whatever).

My issue is that this code will execute twice; once where it passes the output from the selection but does not update the state, then again where it updates the state, but now it does not pass the selection.

So in the code above, the value is ultimately [] on this.state.panelInfo.

#### Observed Behavior
I expected the item value and the state update to execute once with the values passed from the selected item.

#### Steps to Reproduce
The code above should be sufficient to repro.

I also tried using this function for debugging:

```
public _getSelection(item: any, ctx: any) {
    console.log('Selected items:', item);
    ctx.setState({
      showPanel: true,
      panelInfo: JSON.stringify(item)
    });
    console.log(ctx.state);
  }
```

Thanks for any suggestions on how to proceed!

**Comment by kmosti** [comment]
As a workaround, I check in the _getSelection function whether item has a length that is not 0 before changing state, which works.

**Comment by estruyf** [comment]
This due to the `setState` method. The components get triggered to re-render after the properties or state get updated. So in your case, you pass in a new state, so that will re-render all the controls. This is related to how React works.

So in your case, when you select an item, you trigger a re-render by updating the state of the component. Which on its side is going to trigger the selection change handler to return a deselection of the previously selected item.

**Comment by estruyf** [comment]
I tested some things out, and by specifying a `key` in the `DetailsList` control it will not override the selection. This should solve your issue.

**Comment by estruyf** [comment]
An updated package has been released with the bug fix: `@pnp/spfx-controls-react@1.0.0-beta.8`

**Comment by kmosti** [comment]
>Which on its side is going to trigger the selection change handler to return a deselection of the previously selected item.

Ahh, of course. thanks for the update Elio, much appreciated. I will check out the updated package.

**Comment by estruyf** [comment]
Will close the issue as this is fixed since `beta.8`.

**Comment by RicoNL** [comment]
I understand from the comments in this issue that the bug should be solved. 
 However, I'm having the same issue with version 1.11.0 and spfx 1.7.1 . My code is as below. Is there something I should modify in my code to prevent overwriting the selected items?

Thanks for any help on this!

![image](https://user-images.githubusercontent.com/35333175/50638300-98b6c200-0f5d-11e9-96ba-853c11a9bc25.png)

**Comment by carletto75** [comment]
I'm using "@pnp/spfx-controls-react": "^1.15.0",
and selection is still called twice if contains a setState.

First time with real selection and second time with nothing selected.
ListView loses its selection too.

**Comment by Tanddant** [comment]
Seeing same behavior as @carletto75 on "@pnp/spfx-controls-react": "2.1.0"

**Comment by jaxnz** [comment]
Same issue on v2.4.0

**Comment by AJIXuMuK** [comment]
It's a closed thread.

Please, create new issue if you want us to pay attention to it.

Thank you!
