### ISSUE TITLE
People Picker - be able to specify the source site to load users from

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-fx-controls-react#110]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    1.7.0     ]

#### Expected / Desired Behavior / Question
Currently, the People Picker controls is loading users from the current site only, which is limiting usage scenarios as users have different IDs per site. It would be good to be able to specify the source site as this would allow the control to be used cross-site

**Comment by estruyf** [comment]
@joelfmrodrigues thanks for this PR, it got merged and planned for version `1.8.0`.

**Comment by estruyf** [comment]
Closing the issue as version `1.8.0` has just been released.

**Comment by AsishP** [comment]
Thanks @estruyf for looking into this. Sorry I slacked on this, as too many full time projects running right now.
