### ISSUE TITLE
Taxonomy picker is marked up with table element

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-fx-controls-react#113]
#### Category
[ X] Enhancement

[ X] Bug

[ ] Question

#### Expected / Desired Behavior / Question
The markup could be for example a div using flex display. 

#### Observed Behavior
The textbox and the button to open the picker are wrapped in a table element. **Tables should not be used for layout**.

![image](https://user-images.githubusercontent.com/24438807/44578135-bfccde00-a78a-11e8-8c38-4031a976308a.png)

**Comment by estruyf** [comment]
Thanks @Rafaelki for reporting this. This will be in the version `1.8.0` release. More information for testing out a beta can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
Closing the issue as version `1.8.0` has just been released.
