### ISSUE TITLE
IFrameDialog: dialog width is not correct in IE11

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-fx-controls-react#118]
#### Category
[ ] Enhancement
[ ] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question

When specifying a width for the IFrameDialog, it isn't always taken into account on IE11.

**Comment by estruyf** [comment]
Fix for this will be included in version `1.8.0`.

**Comment by estruyf** [comment]
Closing the issue as version `1.8.0` has just been released.

**Comment by AJIXuMuK** [comment]
This fix led to unnecessary scroll inside the IFrameDialog.
