### ISSUE TITLE
Listview - Resizable column widths

### ISSUE THREAD

**Issue by haifoo** [SharePoint/sp-dev-fx-controls-react#119]
#### Category
[x] Enhancement

[ ] Bug

[x] Question

Currently we can only define minWidth/max-width. Im not sure if i just do not know how to properly set this, or if it is not available yet.

**Comment by estruyf** [comment]
Thanks @haifoo for reporting this. I have just implemented the `isResizable` property on the `IViewField` interface. This allows you to specify for each field which can or should not be resizable.

```
const viewFields: IViewField[] = [
  {
    name: 'ListItemAllFields.Id',
    displayName: 'ID',
    maxWidth: 40,
    sorting: true,
    isResizable: true
  },
  {
    name: 'ListItemAllFields.Underscore_Field',
    displayName: "Underscore_Field",
    sorting: true,
    isResizable: true
  },
  {
    name: 'Name',
    linkPropertyName: 'ServerRelativeUrl',
    sorting: true,
    isResizable: true
  },
  {
    name: 'ServerRelativeUrl',
    displayName: 'Path',
    render: (item: any) => {
      return <a href={item['ServerRelativeUrl']}>Link</a>;
    },
    isResizable: true
  },
  {
    name: 'Title',
    isResizable: true
  }
];
```

![column-resize](https://user-images.githubusercontent.com/2900833/45206657-d5abca00-b285-11e8-9f29-1d5871424f68.gif)

This change will be part of the version `1.8.0` release. You can already test out the beta. More information about beta testing: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
Closing the issue as version `1.8.0` has just been released.

**Comment by haifoo** [comment]
thanks for this!
