### ISSUE TITLE
FieldUserRenderer

### ISSUE THREAD

**Issue by FrediLehmann** [SharePoint/sp-dev-fx-controls-react#129]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Version

Please specify what version of the library you are using: [     1.8.0    ]

#### Expected / Desired Behavior / Question
Is it possible to use the 'FieldUserRenderer' Control in a SPFx WebPart or is its usage reserved for list (item) rendering?

#### Observed Behavior
I tried to include the Control like dokumented but now nothing gets rendered.

Source:
``` JavaScript
import * as React from "react";
import styles from "./HelloWorld.module.scss";
import { IHelloWorldProps } from "./IHelloWorldProps";
import { escape } from "@microsoft/sp-lodash-subset";
import { FieldUserRenderer } from "@pnp/spfx-controls-react/lib/FieldUserRenderer";

export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
  public render(): React.ReactElement<IHelloWorldProps> {
    return (
      <div className={styles.helloWorld}>
        <div className={styles.container}>
          <div className={styles.row}>
            <div className={styles.column}>
              <span className={styles.title}>Welcome to SharePoint!</span>
              <p className={styles.subTitle}>Customize SharePoint experiences using Web Parts.</p>
              <p className={styles.description}>{escape(this.props.description)}</p>
              <a href="https://aka.ms/spfx" className={styles.button}>
                <span className={styles.label}>Learn more</span>
              </a>
              <FieldUserRenderer context={this.context} />
            </div>
          </div>
        </div>
      </div>
    );
  }
}
```

#### Steps to Reproduce
1. Create a SharePoint SPFx Project for a WebPart, use the react template.
2. Install the necessery libraries
3. Copy the code from above

Thanks for the help!

**Comment by prokach** [comment]
Hello @FrediLehmann,

Yes, it's possible to use FieldUserRender react component on your WebPart. But it has a visible effect (makes sense) only if you provide at least one user there. 
As for example, you can create a list with a user column(field), create an item there and set it with any user. Afterwards if you open DispForm of the created item you will see a user field value. It's similar to FieldUserRenderer control.
If you want to have PeoplePicker control on your WebPart, please use an appropriate component.
[](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/PeoplePicker)

**Comment by FrediLehmann** [comment]
Hei Oleg

Good to hear, this would solve some future requirements.
Do you have an working example on how tho correctly use this component?
We have already put some time into it but weren't able to make it work correctly.

Thanks in advance.
Greetings
Fredi

**Comment by prokach** [comment]
Hi Fredi,

Yes, I did a WebPart for testing purposes, just for looking at spfx react components.
I hard-coded an array of users with only one item(as mentioned in a documentation, an user object must be IPrinciple type):
```
var myUsers = [];
myUsers.push({
  "id":"9",
  "title":"ABTO ABTO",
  "email":"abto@skybowdev.onmicrosoft.com",
  "sip":"abto@skybowdev.onmicrosoft.com",
  "picture":""
});
```


and put it to a state of a react component:
```
this.state = {
  users: myUsers,
};
```

Then I just imported a component:
`import { FieldUserRenderer } from "@pnp/spfx-controls-react/lib/FieldUserRenderer";`

and used it in a render function:
`<FieldUserRenderer users={this.state.users} context={this.context}  />`

Hope it will help you.

**Comment by AJIXuMuK** [comment]
Is it still an issue/question or can be closed?

**Comment by FrediLehmann** [comment]
Can be closed
