### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-fx-controls-react#13]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Expected / Desired Behavior / Question
@VesaJuvonen any chance to reveal the list of reusable components that may be added to this repository by the Engineering team in the future?
The reason I ask is because this may make people hold back on contributions, thinking that they may be working on something that is already being developed by the team at MS and it would be a "waste" of time to have duplication ( I personally feel that way)

Thanks!

**Comment by estruyf** [comment]
@joelfmrodrigues I will add the ones that are planned in the issue list right away.

**Comment by estruyf** [comment]
I have added the controls which are in the pipeline. If you have other ideas, feel free to share them so we can discuss which might be good to include.

**Comment by joelfmrodrigues** [comment]
@estruyf  Thanks!
The first that immediately comes to mind is a generic web part title, but I believe it was mentioned by Vesa as something that was coming from the Engineering team. Any idea?

**Comment by estruyf** [comment]
Yes indeed, that is also a planned control.
