### ISSUE TITLE
FieldLookupRenderer: Lookup dialog is empty

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-fx-controls-react#131]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question
When clicking on lookup value in `FieldLookupRenderer` the dialog should show lookup item.
#### Observed Behavior
The dialog is empty.
![field-renderer-dialog](https://user-images.githubusercontent.com/17036219/45717213-180abc00-bb4e-11e8-9458-89aef1b838e0.png)
Broken in [https://github.com/SharePoint/sp-dev-fx-controls-react/pull/126](https://github.com/SharePoint/sp-dev-fx-controls-react/pull/126)
#### Steps to Reproduce
Use `FieldLookupRenderer` through `FieldRendererHelper`.
**Remark**: the PR mentioned above fixes the issue if `FieldLookupRenderer` is used separately and `dispFormUrl` has been provided as prop.

**Comment by estruyf** [comment]
This will be available today in version `1.9.0`.
