### ISSUE TITLE
Unnecessary horizontal scroll in IFrame dialog

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-fx-controls-react#132]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question
There is no scroll in `IFrameDialog`

#### Observed Behavior
![iframe-scroll](https://user-images.githubusercontent.com/17036219/45717402-bc8cfe00-bb4e-11e8-8542-8b41f17ac515.png)
broken in #118 
#### Steps to Reproduce
Use `IFrameDialog` control with specified `width`

**Comment by estruyf** [comment]
This will be available today in version `1.9.0`.
