### ISSUE TITLE
Peoplepicker - Move defaultSelectedUsers from ComponentWillMount to ComponentDidUpdate Lifecycle

### ISSUE THREAD

**Issue by AsishP** [SharePoint/sp-dev-fx-controls-react#135]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   1.7.0      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Peoplepicker enhancement to automatically add selected users when the control is loaded.
defaultSelectedUsers should allow preselected users to be set when the control is loaded.

#### Observed Behavior
defaultSelectedUsers doesn't work for complex edit data forms because the data fetch takes time and the peoplepicker component is loaded by then.
Fix - Move the selectedUsers setup step from ComponentWillMount to ComponentDidMount. 
** Mostly I will pick it up soon, but if someone has an urgent requirement of this, please pick it up

**Comment by estruyf** [comment]
The PR is merged and will be available in the latest beta version. Follow this guide in order to test out a beta version: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
This is now available in version `1.10.0`.
