### ISSUE TITLE
Bundle size: decrease the bundle size for latest version of SPFx

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-fx-controls-react#136]
#### Category
[x] Enhancement
[ ] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question

Let the controls use the same version as the latest SPFx version uses. For example, SPFx 1.6.0 uses version 5.120.0 of Office UI Fabric. By using the same version, the bundle sizes can be decreased.

**Comment by estruyf** [comment]
This will be available today in version `1.9.0`.

**Comment by wobba** [comment]
@estruyf will you bump to match SPFx v1.7? As long as we use ouifr v5, you could enter deps to something like «>=5.120.0 <6.0.0», and then the consuming SPFx can set exactly which one they use. I known ouifr uses semver, and hard to see what changes on middle number version. But have yet to see it break.
