### ISSUE TITLE
Peoplepicker - Remove Messagebar error handling and use normal div and textmessage

### ISSUE THREAD

**Issue by AsishP** [SharePoint/sp-dev-fx-controls-react#140]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.7.0 ]

#### Expected / Desired Behavior / Question
Required Message in People Picker is taking too much space when implemented on a form. Need consistency with Office Fabric UI error message handling

#### Observed Behavior
Modify the error message handling of the control to use Office Fabri UI error message format so to keep it consitent with other controls. Basically remove message bar and use normal div elements.

Please provide any further suggestions from the above

Thanks!

**Comment by estruyf** [comment]
The PR is merged and will be available in the latest beta version. Follow this guide in order to test out a beta version: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
This is now available in version `1.10.0`.
