### ISSUE TITLE
TaxonomyPicker retreiving the terms in the correct custom sort order

### ISSUE THREAD

**Issue by trillian74** [SharePoint/sp-dev-fx-controls-react#146]
When i retrieve the terms in a termsett they are sorted alphabetically, but i have applied them with custom sorted list that is defined using the Term Store Management Tool 

#### Category
[ x] Enhancement

[ ] Bug

[x ] Question

#### Version

I'm using @pnp/spfx-controls-react": "1.9.0"
#### Expected / Desired Behavior / Question
I'd like the terms to be listed using the custom sort. Is there a way aleready in place or is it "missing"?

#### Observed Behavior
When i retrieve the terms in a termsett they are sorted alphabetically, but i have applied them with custom sorted list that is defined using the Term Store Management Tool 

#### Steps to Reproduce
Add custom sort and review the listing. Its unchanged

**Comment by trillian74** [comment]
After reviewing /src/services/SPTermStorePickerService.ts i think i have a fix with a default where if the termSet has its CustomSortOrder property set then it will use that as the sort instead of the default sort.

`// inside getAllTerms, need to check null on CustomSortOrder`
`term.SortOrderIndex = termStoreResultTermSet.CustomSortOrder.split(":").indexOf(this.cleanGuid(term.Id));`

Then you'd have the SortOrderIndex on each term in the set and thus sort it based on the custom sort entered in the term management tool

I'm not that familiar to take part in open source development, but if you have some direction on how to contribute i'll happily share my fix.

Ole

**Comment by trillian74** [comment]
I've added some code to the dev. What is the process to get it release as @next or master? @estruyf

**Comment by estruyf** [comment]
@trillian74 thank you very much, I will process this later this week.

**Comment by trillian74** [comment]
thx @estruyf i guess its not default that the contribution gets in, but when do i know if it get thru or not?

**Comment by AJIXuMuK** [comment]
If the PR is still open then @estruyf just hasn’t had time yet to process it. He’ll comment when it’s processed.

**Comment by estruyf** [comment]
This is now available in version `1.10.0`.
