### ISSUE TITLE
[IFrameDialog] Loader (Spinner) is appears constantly

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-fx-controls-react#154]
#### Category
[ x] Enhancement

[ X] Bug

[ ] Question

#### Version 1.9.0

Hi,
there is a bug in IFrameDialog, the loader (spinner) is appears constantly (bug appear only in 1.9.0) : 

![iframe](https://user-images.githubusercontent.com/582733/47210333-f9892200-d392-11e8-90a2-a08ce2b2908e.png)

I have another suggestion, is it possible to add an option to add parameters to the iframe ?

ex for youtube embed to add "allowfullscreen" parameters:
<iframe src = "//www.youtube.com/embed/fgdvd4545?autoplay=1" allowfullscreen></ iframe>

Thanks

**Comment by estruyf** [comment]
@AJIXuMuK could you check this one?

**Comment by AJIXuMuK** [comment]
Will look into it

**Comment by estruyf** [comment]
@PooLP fix for this will be included in version `1.11.0` thanks to @AJIXuMuK.

**Comment by PooLP** [comment]
Thanks @AJIXuMuK

**Comment by estruyf** [comment]
This has been released with the latest `1.11.0` version. Feel free to test it out, and you can reopen the issue if it still occurs.
