### ISSUE TITLE
Using a control in SharePoint Top Placeholder

### ISSUE THREAD

**Issue by asadullah313** [SharePoint/sp-dev-fx-controls-react#155]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

I am developing a SharePoint SPFx Placeholder. One of the items in the placeholder must be security trimmed. I'm therefore using the SecurityTrimmedControl to achieve that. But in the SPFx documentation the HTML that is rendered into the Top Placeholder is insereted into an innerHTML property like this:

```
this._topPlaceholder.domElement.innerHTML = 
`
<HTML for Placeholder>

`
```

I have tried to insert the following in the innerHTML:

```
<SecurityTrimmedControl context={this.props.context} level={PermissionLevel.remoteWeb} remoteSiteUrl="https://[tenant].sharepoint.com/sites/[site]" permissions={[SPPermission.viewPages]}>
  <p>I have access</p>
</SecurityTrimmedControl>
```

But this does not work. How can I make it work with the innerHTML property?

Thanks in advance!

**Comment by PooLP** [comment]
Hi,
SecurityTrimmedControl is a React component so this don't work with simple innerHTML.

**Comment by AJIXuMuK** [comment]
Here is an [example](https://github.com/SharePoint/sp-dev-fx-extensions/tree/dev/samples/react-application-duetasks) how to add React control in the header.
Hope it helps.

**Comment by asadullah313** [comment]
Thanks for the help

**Comment by asadullah313** [comment]
> Here is an [example](https://github.com/SharePoint/sp-dev-fx-extensions/tree/dev/samples/react-application-duetasks) how to add React control in the header.
> Hope it helps.

Please forgive my ignorance. I am new to React and i am trying to figure out how to add that React SecurityTrimmedControl to the innerHTML :)

This is the innerHTML from the project example you mentioned:

**Comment by AJIXuMuK** [comment]
Sorry, my bad!
Forgot that this one just uses Fabric styles but not the components.
Here is another link: [https://github.com/SharePoint/sp-dev-fx-extensions/tree/dev/samples/react-application-office-groups-nav](https://github.com/SharePoint/sp-dev-fx-extensions/tree/dev/samples/react-application-office-groups-nav)

and the example:
```typescript
private _renderPlaceHolders(): void {

    // Handling the top placeholder
    if (!this._topPlaceholder) {
      this._topPlaceholder =
        this.context.placeholderProvider.tryCreateContent(
          PlaceholderName.Top,
          { onDispose: this._onDispose });

      // The extension should not assume that the expected placeholder is available.
      if (!this._topPlaceholder) {
        return;
      }

      if (this._topPlaceholder.domElement) {
        const component: React.ReactElement<IGroupsNavigationProps> = React.createElement(GroupsNavigation, {
          groups: this._groups
        });
        ReactDOM.render(component, this._topPlaceholder.domElement);
      }
    }


  }
```

So, it's pretty easy. And don't forget to import React and ReactDom:
```typescript
import * as React from 'react';
import * as ReactDOM from 'react-dom';
```

**Comment by asadullah313** [comment]
Thank you. It took me some time to figure out how to convert the whole thing to a component and then import it. Thank you :)
