### ISSUE TITLE
FileType icon and .pdf

### ISSUE THREAD

**Issue by Leif-Frederiksen** [SharePoint/sp-dev-fx-controls-react#17]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://github.com/SharePoint/sp-dev-fx-controls-react/wiki) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   1.0.0-beta.8      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
When giving af path that ends in .pdf I would expect to get a PDF icon.

#### Observed Behavior
No application specific icon is given - just the default icon (white shet of paper like thing).

#### Steps to Reproduce
Create a webpart and render <FileTypeIcon path="something.pdf">

**Comment by estruyf** [comment]
@Leif-Frederiksen when the control was released, Office UI Fabric didn't contain a PDF icon yet. Apparently, it has it right now, so will check if we can use it in the control set.

**Comment by estruyf** [comment]
@Leif-Frederiksen my mistake, it seems that there is still not a PDF image icon. Only the font icon, which should be working fine.

So if you are using it as follows it should work:

```
<FileTypeIcon type={IconType.font} path="https://contoso.sharepoint.com/documents/filename.pdf" />
```

At the moment it does not work with the `IconType.image` option.
