### ISSUE TITLE
PeoplePicker titleText property should not be required

### ISSUE THREAD

**Issue by bpringe** [SharePoint/sp-dev-fx-controls-react#175]
#### Category
[ x ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: 1.10.0

#### Expected / Desired Behavior / Question
The `titleText` property of the PeoplePicker (and other controls) should not be required, as is the case with many other third party react input controls. It should be optional. The user should be able to render the control without a title, or perhaps in a table cell where the title is in the header of the column.

#### Observed Behavior
The `titleText` property of the PeoplePicker is required, and if an empty string is given, it renders a default title.

**Comment by estruyf** [comment]
This will be included in version `1.11.0`.
