### ISSUE TITLE
Taxonomy Picker - Incorrect sort order

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-fx-controls-react#205]
#### Category
[ ] Enhancement
[X] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [1.11.0 beta]

#### Expected / Desired Behavior / Question
In the panel view of the Taxonomy Picker (an awesome control all around!), lower case terms are ending up at the bottom of the listing. (See example below).

#### Observed Behavior
![image](https://user-images.githubusercontent.com/1295627/50227573-05359c80-0374-11e9-8259-97124c7e853e.png)

#### Steps to Reproduce
Create and use a Term Set with lower and upper case terms and look at it in the picker

**Comment by estruyf** [comment]
Thanks @sympmarc, will get this fix for the release today.

**Comment by estruyf** [comment]
Fix is in, so will be released with `1.11.0`.

**Comment by sympmarc** [comment]
You rock.

**Comment by estruyf** [comment]
This has been released with the latest `1.11.0` version.

**Comment by amarmechai** [comment]
Not completely fixed, there is a problem with the accents.

![image](https://user-images.githubusercontent.com/4630877/50829314-5d910600-1344-11e9-8b09-486b68dcbb33.png)
