### ISSUE TITLE
New Control: Taxonomy Picker

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-fx-controls-react#22]
[x ] Enhancement

A taxonomy picker control that works similarly to the classic one.

**Comment by AJIXuMuK** [comment]
@russgove, @estruyf 
there is a term picker control for Property Pane ([https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyFieldTermPicker/](https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyFieldTermPicker/)).
Does it make sense to just "transfer" this control to this repo as well?

**Comment by spdavid** [comment]
@estruyf @russgove 
I'm thinking the best thing would be to create something similar to the OOB picker and have suggestions when typing and have the picker icon that has similar behavior to the Property Pane Picker with a popup or panel from the side. I'm looking for a good challenge and can work on this one if nobody else has started yet.

**Comment by estruyf** [comment]
That is great @spdavid. It might be interesting to get it first included in the Property Pane controls project. Here is the corresponding feature request: https://github.com/SharePoint/sp-dev-fx-property-controls/issues/11

**Comment by spdavid** [comment]
Ok sounds good. Ill start with it there and then port it over to this repo.

**Comment by AJIXuMuK** [comment]
Hi @spdavid ,

Do you have any plans on when you'll working on it? *shy* :)

I need that kind of control in my current project and am planning to work on it in next two weeks or so...
So, just wanted to know if there is a probability that you'd finish yours or I'll just need to work in parallel :)

**Comment by spdavid** [comment]
I plan on having the property control version fixed this weekend. And port it over to this one during the beginning of next week.

**Comment by AJIXuMuK** [comment]
@spdavid that's awesome! :)

**Comment by spdavid** [comment]
@AJIXuMuK Just a  status update for you :). Got pretty far on the weekend. Just need to style a bit and set up the tests. I opted to use the base picker from the fabric UI so i can customize it a bit more and use a custom interface and rendering. So its taking a bit longer. Might not have so much time this week but I will be finishing up this upcoming weekend.

**Comment by AJIXuMuK** [comment]
Thanks @spdavid! I really appreciate that you're informing me :)
Most probably I'll start with some basement by end of this week but will look forward to hearing from you :)

**Comment by spdavid** [comment]
https://github.com/SharePoint/sp-dev-fx-property-controls/pull/39

Pull request made in the sp-dev-fx-property-controls repo. Will port over the code to this repo next. 

But a few things to discuss.  Do we want this Taxonomy Picker to search through the termstore, group and termset. I'm thinking termset, all terms, and perhaps enterprise keywords.  I have found the group scenario is a bit tricky and the api does not support it in a good way. 

Feedback on this matter is welcome 👍

**Comment by AJIXuMuK** [comment]
I would say that it should be also "filterable" to a specific term.
Use Case: Managed Metadata Field that is tied to a Term, not Term Set.

Additionally, if I remember correctly, the initial `PropertyFieldTermPicker` control's tree doesn't support nested terms (terms in terms)...

**Comment by estruyf** [comment]
@spdavid great! Thanks for contributing.

I would limit it to a specific term set, not a group / multiple term sets as this is the functionality the other term picker control provides.

**Comment by spdavid** [comment]
Great. Almost finished. Limited to a termset only and have AnchorId as an optional prop. Will be ready in a day or two.

**Comment by AsishP** [comment]
@spdavid, how soon could you have a complete control for any dev use. I am getting a push for a similar control from my team. I am asking them to wait with hopes to not reinvent the wheel. May be we can use a dev copy to evaluate while this control comes to fruition. Happy to contribute for it too and move it faster.

Sorry for the push but would not want us to reinvent the wheel if we can use this control.

**Comment by spdavid** [comment]
@AsishP 
Thanks for your comment. I'm literally a few hours a way from finish.  Tonight or tomorrow morning. Its been a busy week and I'm developing it in my free time as I'm to busy with my regular work. Almost ready.

**Comment by AsishP** [comment]
@spdavid, no probs. Thanks for looking to prioritize this.

**Comment by spdavid** [comment]
@AsishP Pull Request made.

**Comment by AsishP** [comment]
@spdavid, thanks for the update. Will get the PR and use it for future implementations. In current case, because of urgency, we happen to implement our own version of Taxonomy control extracting the logic from property pane picker control in [https://github.com/SharePoint/sp-dev-fx-property-controls.](url)

Quick fyi, found an issue with use of termset GUID in the code from property pane picker control. If you are using the same logic. please see the fix here in the issue submitted - SharePoint/sp-dev-fx-property-controls#48

Thanks again.

**Comment by estruyf** [comment]
@AsishP I have added the same change as to the property control. 

The `TaxonomyPicker` control is now available in the latest beta release. Feel free to check it out.

More information about installing beta versions can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/
