### ISSUE TITLE
Question regarding ControlStrings

### ISSUE THREAD

**Issue by CharlieDLee** [SharePoint/sp-dev-fx-controls-react#220]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

1.11.0

#### Question

I have added the component (npm install) and added the ControlStrings entry in config.json, but when I serve the code and navigate to the workbench on Office 365 (not the local workbench) I get an error stating:
 ```
[SPLoaderError.loadComponentError]:
***Failed to load component XXX.
Original error: ***The entry point for component XXX has a dependency on "ControlStrings" that is not declared in the manifest.
```
The web part works fine on the local workbench, but I want to use the ListItemPicker with some SharePoint lists from an existing site without deploying the web part there.

Is this possible?  Am I missing a step somewhere?
 
Thanks!

**Comment by AJIXuMuK** [comment]
Hi @CharlieDLee,
Could you please provide your code or more details?
I've just tested it on 2 tenants and it works fine.
I'm using SPFx v1.7.1 and controls v1.11.0.

Note: with v1.11.0 you don't need to set anything in `config.json` by yourself. The path for localization resources is configured automatically during installation. Please, reference the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/).

Have you done `gulp trust-dev-cert`?

**Comment by CharlieDLee** [comment]
Thanks Alex

SPFx v 1.7.1-plusbeta (I am developing a web part for deployment in Teams)

I did not manually add the ControlStrings entry it was added by npm install so that should be ok

Nothing clever in the web part as I am just checking the basic plumbing before adding styling and additional logic.

Render method in base web part  
```
public render(): void {
    
    var teamName: string;

    if(this._teamsContext)
    {
      teamName = this._teamsContext.teamName;
    } else {
      teamName = "NOT IN TEAMS.";
    }
    
    const element: React.ReactElement<ICallLoggingWebPartProps > = React.createElement(
      CallLoggingWebPart,
      {
        description: this.properties.description,
        teamsTitle: teamName,
        context: this.context
      }
    );

    ReactDom.render(element, this.domElement);
  }
```

Web Part Properties Interface
```
import { DayOfWeek } from 'office-ui-fabric-react/lib/DatePicker';
import { WebPartContext } from '@microsoft/sp-webpart-base';

export interface ICallLoggingWebPartProps {
  description: string;
  teamsTitle: string;
  context: WebPartContext 
}
```

Example of control rendering from React component
```
<Label>Enquiry type:</Label>
<ListItemPicker listId='5b915735-63bb-4248-a36a-c98b8dc0498e'
    columnInternalName='Title'
    itemLimit={1}
    onSelectedItem={this.onSelectedEnquiryType}
    context={this.props.context} /> 
```

Anything else you might need to see?

Thanks

Charlie

**Comment by CharlieDLee** [comment]
Oh and yes I have run the gulp task to trust the dev certificate.

**Comment by AJIXuMuK** [comment]
hmmm...
Maybe it's somehow related to the environment you have. 
What OS, node and npm version do you use?

I've also shared my project with the code you provided (the difference - I've changed list id).
You can check it [here](https://github.com/AJIXuMuK/issues/tree/master/sp-dev-fx-controls-react-220).
It completely works for me. If it doesn't for you then I bet it's environment issue.
For example, NodeJS version - SPFx works well with version 8.

**Comment by CharlieDLee** [comment]
Thanks Alex.  I was running node 8.12.0 on Windows 10.  I noticed that the SPFx docs are currently recommending 8.15.0 so I switched to that in NVM and it started working ok.  I then switched back to 8.12.0 and it still worked...  I'm calling this 'one of those things' and moving on - thanks for your help.
