### ISSUE TITLE
Any interest in a Pagination Control and/or Carousel Control?

### ISSUE THREAD

**Issue by hugoabernier** [SharePoint/sp-dev-fx-controls-react#227]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Question

A while ago, I created a pagination control for the [Calendar Feed Web Part Sample](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-calendar-feed), which was designed to mimic the out-of-the-box SharePoint Events web part.

I also created a carrusel control that allows you to scroll through items in a wide or narrow style, much like the out of the box SharePoint web parts.

![Calendar Feed Wide](https://user-images.githubusercontent.com/13972467/51628696-b3080e00-1f13-11e9-87e7-1c6b7c834905.png)

![Calendar Feed Narrow](https://user-images.githubusercontent.com/13972467/51628729-ca46fb80-1f13-11e9-883b-1a0f149523e8.png)

This layout is becoming more and more used throughout SharePoint, for example the Sites web part:

![Sites -- Wide Layout](https://user-images.githubusercontent.com/13972467/51627276-a1bd0280-1f0f-11e9-8fae-453577fa4ab2.png)

![Sites -- Narrow](https://user-images.githubusercontent.com/13972467/51627308-b9948680-1f0f-11e9-8596-bfbd973c784a.png)

When I demoed the Calendar Feed web part during SPFx SIG call, I got a lot of feedback from attendees saying I should submit the control to the PnP controls.

The controls are already designed to allow any type of "items", not just events. You could insert document previews, etc.

You can see the existing code in the [component's folder in the repo](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-calendar-feed/src/shared/components). It contains `CarouselContainer`, `DateBox`, `EventCard`, and `Paging` controls, but (unless it would be useful to anyone), I'm only proposing to create a `CarouselContainer` and `Paging` control.

I'd be happy to submit this, but I want to make sure I'm not wasting anyone's (including mine) time.

Is this something that would be useful for anyone?

**Comment by gautamdsheth** [comment]
Yes, absolutely. Would love to see this implemented, especially the Pagination control. For pagination, would like to see couple of other options such as (Prev/Next) along with Page numbers something similar to React bootstrap with the Fabric UI flavour !

**Comment by estruyf** [comment]
This could indeed be a great addition to the project. Just for the extensibility of this control, I would make it so that the items which are rendered, are passed as React components to the control. That way, you can use it for whatever you want.

**Comment by estruyf** [comment]
The new `Carousel` control has been merged and is now available to test out in the latest beta release. More information on how you can install a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
Closing this issue as version `1.15.0` has just been released.
