### ISSUE TITLE
WebPartTitle: Add the ability to render a custom control

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-fx-controls-react#228]
#### Category
[x] Enhancement
[ ] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question

Add the ability to render a custom control next to the title. This allows developers to easily create links like the default `see all` link, but can also be used to add more than that.

**Comment by jonathanhotono** [comment]
I really need this kind of feature to display the "See all" link as customers are starting to ask us to made this as well. But things to consider here:
1. If webpart title is empty, we still need to display the custom control
2. If webpart is on classic page?

**Comment by hugoabernier** [comment]
@estruyf and @jonathanhotono: I just submitted a PR that does a slight variation on this.

I added the ability to pass children in the `moreLink` prop, which will allow developers to easily add custom components in the right-side of the title -- thus giving you the "See all". 

The web part title will render if a title is provided _or_ if a `moreLink` is provided.

I did not provide custom rendering logic for the web part title itself as I figured that if someone wants to completely render a custom web part title, they can probably do so easier within their own web part than through the web part title control.

I'd be happy to revise my approach if you prefer :-)

**Comment by estruyf** [comment]
I will test it out @hugoabernier. Think it already gives enough flexibility to the developer.

**Comment by estruyf** [comment]
This will be part of the `1.13.0` release. You can already test out the functionality by installing the latest beta: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
The new version is now building and will be released in a couple of minutes.
