### ISSUE TITLE
Can't clear PeoplePicker value(s)

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-fx-controls-react#234]
#### Category
[ ] Enhancement
[X] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [1.11.0 ]

#### Expected / Desired Behavior / Question
I'd like to be able to clear the value(s) selected in the PeoplePicker programmatically. In my specific case, I'm using the People Picker to select a person to use for filtering a listof items.

#### Observed Behavior
When I set defaultSelectedUsers to [] (an empty array), the previously selected value remains.

#### Steps to Reproduce
Here's an example of my code for defaultSelectedUsers:
``` typescript
defaultSelectedUsers={(this.state.filters.ShipmentRequestor && this.state.filters.ShipmentRequestor.length) ? [this.state.filters.ShipmentRequestor.email] : []}
```
This will either yield an array of email addresses or an empty array.

**Comment by estruyf** [comment]
@sympmarc included the fix from @tsekityam. Can you verify if it fixed it on your end by installing the latest beta version?

**Comment by sympmarc** [comment]
Sorry I haven't replied. I'm heading home from SPTechCon today and will test tomorrow.

**Comment by estruyf** [comment]
No problem @sympmarc, have fun at SPTechCon and say hi to @sebastienlevert.

**Comment by sympmarc** [comment]
Works for me! Thanks for the update, @tsekityam.
