### ISSUE TITLE
How to create a property control used for dev controls?

### ISSUE THREAD

**Issue by hugoabernier** [SharePoint/sp-dev-fx-controls-react#239]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Expected / Desired Behavior / Question

Let's say that you're building a developer control for the sp-dev-fx-controls-react library, and you want to add a property pane control that works in conjunction with the dev control.

What would be the best approach to do so?

For example, in my updated Rich Text control, I created a panel control that gives users the ability to format text (in a fashion similar to the out-of-the-box richtext control's **More** button). 

Here is the RTE control with the **More** button:
![image](https://user-images.githubusercontent.com/13972467/52798387-d5d69f80-3045-11e9-9bc6-97ffcabe3c7d.png)

And here is the formatting panel:
![image](https://user-images.githubusercontent.com/13972467/52798562-2948ed80-3046-11e9-82d9-46bdf6f3fdae.png)

(yes, I know they look like the out-of-the-box controls, that's the point!!!)

However, it uses the Office Fabric Panel control, because we don't know if -- when the RTE control is used -- if the Web part panel will be available.

I would like to expose the formatting panel as an optional property pane control and allow developers who use the RTE control to optionally use the formatting property panel in their own web part property panes as they see fit.

It wouldn't be for v1 of the RTE control, but I'm asking for future considerations.

My concerns are as follows:
- Adding the RTE formatting property pane control to the dev controls may work, but PnP has always been really good at keeping the distinction between the dev controls and the property controls.
- Adding the property pane formatting control in the property controls library, and the RTE control in the dev controls and then adding a reference to the property controls from the dev controls would potentially add an unnecessary reference
- Keeping each control in their respective libraries may work, but it would require developers to add both the dev control and the property controls to their solutions. (Which isn't a bad thing, really). 

The last option may work, but I want to make it possible to use only the RTE control without requiring devs to customize the property pane control, which would mean that we have duplicate code (one version of the formatting pane as a dev control, one version as a property pane control).

What would be the best approach?

Thanks everyone for your help!

**Comment by estruyf** [comment]
Best is to keep them separate, that way if we or someone else in the future decides to make an Angular/Vue/web components library out of this one, only these controls have to be managed. 

It also makes a lot of sense from a property pane control, if something gets changed to any of the APIs. It only needs to be done on that project, and not in this one as well. 

IMO nothing is wrong with adding the other library as a dependency. It's the developer choice to choose what they want to leverage from the libraries. It could be for instance that they will use the control in an application customizer, which can't even use the property pane controls.

**Comment by hugoabernier** [comment]
Thanks @estruyf. Makes sense. I'll make the changes accordingly.
