### ISSUE TITLE
Cannot use controls

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-fx-controls-react#25]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://github.com/SharePoint/sp-dev-fx-controls-react/wiki) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

After running install and trying to use a control like this:
import {ListView} from "@pnp/spfx-property-controls";

I get an error saying, 
Cannot find module '@pnp/spfx-property-controls'.

The "main" is missing from package.json

**Comment by estruyf** [comment]
Merged your PR. For your bundle size, it is best to be specific to which controls you want to add. For ListView this is: `from "@pnp/spfx-controls-react/lib/ListView";`. 

As your PR #26 is merged to the DEV branch I close this issue.
