### ISSUE TITLE
WebPartTitle add support for section background color

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-fx-controls-react#258]
#### Category
[ x ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   1.12.0      ]

Can we add support to section backgrounds font color for WebPartTitle ?
![image](https://user-images.githubusercontent.com/6864547/54903630-f0d2e400-4f0e-11e9-9596-d46b06e1f55b.png)

Probably need user to optionally add a `themeVariant` object into the component optionally, and if themeVariant object exist we use `themeVariant.semanticColor.bodyText`
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds

**Comment by mpowney** [comment]
Hi @estruyf - this sounds like a useful enhancement to make. I'd be happy to pick this up as my first contribution to this project, any thoughts?

**Comment by estruyf** [comment]
The PR from @mpowney just got merged, and this change will be available in version `1.14.0`.

If you want, you can already test it out via installing the latest beta version. More information about how to install a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
This is now included within the `1.14.0` release
