### ISSUE TITLE
How to render list's views

### ISSUE THREAD

**Issue by jarkaos** [SharePoint/sp-dev-fx-controls-react#267]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [ ^1.12.0   ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Is the ListView control capable to render custom list's views? 
I have a list with 4 views (mostly filtering) and 2 grouped views. The grouped views works fine with ListView component but I can't find the way to render the other views.
I know that there is a filter property but is not enough to show what the views contains. Ex. a view filters all items whos end date has passed. 

Thanks!

**Comment by sympmarc** [comment]
In building your Web Part in SPFx, the ListView control is really a helper capability for you. It’s not what you think of as a SharePoint list view - it’s the Office UI Fabric ListView with some added plumbing to use with SPFx Web Parts. If you want to have multiple “views”, you’ll need to build them in your code.

**Comment by jarkaos** [comment]
> In building your Web Part in SPFx, the ListView control is really a helper capability for you. It’s not what you think of as a SharePoint list view - it’s the Office UI Fabric ListView with some added plumbing to use with SPFx Web Parts. If you want to have multiple “views”, you’ll need to build them in your code.

Thanks for your comments. 
I found that, maybe, the simpliest way is send a new request to sharepoint and re render the ListView component. 
So I am trying that.

Best regards
