### ISSUE TITLE
Incorrect usage of ms-PeoplePicker class

### ISSUE THREAD

**Issue by effectivetom** [SharePoint/sp-dev-fx-controls-react#275]
https://github.com/SharePoint/sp-dev-fx-controls-react/blob/77788376d4cb1ce7ab530b2f986d21ff33e33e3b/src/controls/peoplepicker/PeoplePickerComponent.tsx#L196

The single quotes around `ms-PeoplePicker` weren't removed when the className property was [changed to use a template literal](https://github.com/SharePoint/sp-dev-fx-controls-react/commit/62d2727fe0202d8dd4d5473050f6b88de7297934). This results in them being rendered to the DOM and the class name not being applied correctly.

**Comment by estruyf** [comment]
@effectivetom good find, this will be fixed in the upcoming release.

**Comment by estruyf** [comment]
This is now in the process to be released.
