### ISSUE TITLE
Adding Rich Text Makes drop-downs turn black

### ISSUE THREAD

**Issue by araver** [SharePoint/sp-dev-fx-controls-react#279]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.13.0 ]

#### Expected / Desired Behavior / Question
Rich text control shouldn't make other drop-downs turn black

#### Observed Behavior
Rich Text Control turns other drop-downs black

#### Steps to Reproduce
Add a dropdown and a Richtext control and the dropdown will turn black

With Rich Text control
![image](https://user-images.githubusercontent.com/31546277/56690298-652dae00-669a-11e9-83c6-dc959277274e.png)

Without Rich Text Control
![image](https://user-images.githubusercontent.com/31546277/56690374-8abab780-669a-11e9-8e1c-de1c2e2a5e6a.png)

**Comment by hugoabernier** [comment]
@araver good catch. I'm afraid my SCSS selectors were a bit overzealous.

I've submitted a fix for this issue. 

Sorry for the inconvenience!
