### ISSUE TITLE
List view doesn't rendering anything

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-fx-controls-react#28]
I am using SharePoint Framework React controls's [list view](https://github.com/SharePoint/sp-dev-fx-controls-react/wiki/ListView) to render the items from document library. I am able to get the items from library by selecting the list from dropdown. But While rendering the items, it is not showing any items in the view. But, when i click on item I am able to write data in that row in console. It is rendering like below:
![spfx-reactcontrols_render](https://user-images.githubusercontent.com/7568187/34493443-eb4428ee-f011-11e7-8729-4180cee84cf9.PNG)
I am using ListView like below
```
<ListView
            items={this.state.listData}           
            iconFieldName="ServerRelativeUrl"
            compact={true}
            selectionMode={SelectionMode.multiple}
            selection={this._getSelection}
             />   
```         

[X] Question

**Comment by estruyf** [comment]
Hi @ymihir have you already tried specifying the `viewFields` property? Here is an example:

```
const viewFields: IViewField[] = [
      {
        name: 'ListItemAllFields.Id',
        displayName: 'ID',
        maxWidth: 40,
        sorting: true
      },
      {
        name: 'ListItemAllFields.Underscore_Field',
        displayName: "Underscore_Field",
        sorting: true
      },
      {
        name: 'Name',
        linkPropertyName: 'ServerRelativeUrl',
        sorting: true
      },
      {
        name: 'ServerRelativeUrl',
        displayName: 'Path',
        render: (item: any) => {
          return <a href={item['ServerRelativeUrl']}>Link</a>;
        }
      },
      {
        name: 'Title'
      }
    ];
```

**Comment by ymihir** [comment]
@estruyf but as per the [documentation ](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/ListView/#implementation)viewFields is optional right! I need to pass the structure compulsory? 
I am implementing this with [PropertyFieldListPicker](https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyFieldListPicker/). When I select any list and if i reload the page, earlier selection is not preserving. Dropdown value coming as blank. Any idea about this issue?

**Comment by estruyf** [comment]
Yes, it is, but in combination with the `iconFieldName` it will only show the icon. If you would remove the `iconFieldName`, the control itself will define the fields to show.

**Comment by ymihir** [comment]
Yes, Perfect Once i remove the `iconFieldName` it is showing as below with raw data. Any idea with second issue where dropdown value is not preserving as showing in second screenshot.
![spfx-reactcontrols_render_nolist](https://user-images.githubusercontent.com/7568187/34517724-3c1cb03e-f0a2-11e7-84d2-6f9d6c12adc2.PNG)

![spfx-reactcontrols_render_fine](https://user-images.githubusercontent.com/7568187/34517680-078b1874-f0a2-11e7-8d78-e9603cee6e5f.PNG)

**Comment by estruyf** [comment]
That could be a bug in the Office UI dropdown control. Which version of the SPFx are you using? If possible, can you also check the installed version of `office-ui-fabric-react`?

**Comment by ymihir** [comment]
i am having office-ui-fabric-react version as 5.6.0

**Comment by estruyf** [comment]
@ymihir did you update the `targetProperty` to the property in your web part. This was incorrectly documented and updated it: https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyFieldListPicker/

So `lists` must be the same on line 1 ('lists') and 3 (this.properties.lists):

```TypeScript
PropertyFieldListPicker('lists', {
  label: 'Select a list',
  selectedList: this.properties.lists,
  includeHidden: false,
  orderBy: PropertyFieldListPickerOrderBy.Title,
  disabled: false,
  onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
  properties: this.properties,
  context: this.context,
  onGetErrorMessage: null,
  deferredValidationTime: 0,
  key: 'listPickerFieldId'
})
```

If you copied it from the documentation, you would probably have `singleList` which is not correct.

**Comment by ymihir** [comment]
Yes I have sorted out that issue. Thanks for the documentation update.

**Comment by jburagev** [comment]
Hello,

I have similar issue where I defined the ViewFields:

export const  viewFields : IViewField []= [{    
  name: "Car",    
  displayName: "Car",    
  //linkPropertyName: "c",    
  isResizable: true,    
  sorting: true,    
  minWidth: 0,    
  maxWidth: 150,
  render: (item:any) => <div>{item.Car['Car']}</div>    
},{    
  name: "DistanceKm",    
  displayName: "Distance",       
  isResizable: true,    
  sorting: true,    
  minWidth: 0,    
  maxWidth: 100    
},];

But the Car field is not rendered and I get error. Each other field is rendered as it should. I tried every combinations like item.Car.Car, item['Car'].Car etc. I receive the items from Sharepoint as following:

![image](https://user-images.githubusercontent.com/24312918/100109649-573ea100-2e6c-11eb-9262-9939c142bdc4.png)

The error that i got is:

![image](https://user-images.githubusercontent.com/24312918/100109959-b2709380-2e6c-11eb-9f2a-64c8dbd8baeb.png)

Please help.

Thanks.
