### ISSUE TITLE
listItemAttachments render Issue

### ISSUE THREAD

**Issue by jesusrq** [SharePoint/sp-dev-fx-controls-react#282]
#### Category
[ ] Enhancement
[x] Bug
[ ] Question

Please specify what version of the library you are using: [ **1.13.0** ]
![Screenshot_4](https://user-images.githubusercontent.com/45797480/56750718-fc9e0a00-6749-11e9-92de-2dbba7692acd.png)

**Expected / Desired Behavior / Question**

In the **listItemAttachments** control,  at the very end when you delete a file it should render again.

**Observed Behavior**
The  **listItemAttachments**  control doesn't render fine after the click of deleting a file. 

**Steps to Reproduce**
Delete a file and follow the steps. At the and after the file has been deleted, the component won't render fine.

**Submission** Guidelines
I think is a problem with the **DocumentCardPreview**

Thanks!

**Comment by estruyf** [comment]
This fix will be included in version `1.8.2`. Feel free to test out the latest beta to see it fixes the issue. Here you can read more information on how you can test out the latest beta version: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
This has just been released in the version `1.13.2`.
