### ISSUE TITLE
WebPartTitle styles while in edit mode override the styles set by className.

### ISSUE THREAD

**Issue by parithon** [SharePoint/sp-dev-fx-controls-react#29]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  1.1.1       ]

#### Expected / Desired Behavior / Question
When switching between 'live/preview' to 'edit' mode my className styles should still prevail.

#### Observed Behavior
When switching between 'live/preview' to 'edit' mode the styles set by the className are overridden by the controls 'edit' style. The problem is that I may be using a background color that is close or matching the style used in edit mode making the text unreadable. Additionally, it doesn't allow you to see the true styles of the title while in edit mode.

#### Steps to Reproduce
Set the className for the WebPartTitle component. Start the workbench and switch between Preview and Edit mode.

**Comment by estruyf** [comment]
Thanks for reporting this. I'll see how we can fix this.

**Comment by estruyf** [comment]
I have pushed a fix to the DEV branch for this that allows the control to inherit the color. You can already test it out via the beta release: `@pnp/spfx-controls-react@1.1.2-beta.c51703a`.

**Comment by estruyf** [comment]
Closing this issue as it is fixed in the current version.
