### ISSUE TITLE
ListItemPicker could be a combo box

### ISSUE THREAD

**Issue by Katli95** [SharePoint/sp-dev-fx-controls-react#292]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.11.0]

#### Desired Behavior
Hi guys, as always, love your work! 
I set up the `<ListItemPicker/>` and expected it to be a ComboBox derived control, which of course it isn't today :/ I feel that if it were it would be a great enhancement of the UX. As a user I may not know the exact value I'm looking for and would like to select an item from the list, given the list contains relatively few items (For my requirements it is a status field containing 7 values).

In addition I'd like to be able to set the selected items by ID only, instead of providing the entire item.

**Comment by mellolr1** [comment]
> In addition I'd like to be able to set the selected items by ID only, instead of providing the entire item.

The flexibility to select the value and name would be great. In my case, I need to display two columns as the name and a third column as the value.

**Comment by mellolr1** [comment]
@estruyf, I can give this a try.
