### ISSUE TITLE
TaxonomyPicker Cannot find name 'TermLabelAction'

### ISSUE THREAD

**Issue by JarecN** [SharePoint/sp-dev-fx-controls-react#293]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ 1.12.0 ]

#### Question
Hi!

I am trying to add default TermLabelAction using code below, but VS Code keeps telling me "Cannot find name 'TermLabelAction'. **What should I import to make that work?**

termActions={{
            actions: [new TermLabelAction("Get Labels")]
          }}

Cheers
-Jarkko

**Comment by estruyf** [comment]
Thanks @JarecN for reporting this.

Seems that this class was not exported correctly. I have implemented a fix for this which will be included in version `1.13.2`. Please feel free to test out the latest beta.

Here you can read more information on how you can test out the latest beta version: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
This has just been released in the version `1.13.2`.
