### ISSUE TITLE
should items be an array of type any

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-fx-controls-react#3]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://github.com/SharePoint/sp-dev-fx-controls-react/wiki) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

[x] Cpmment

In the ListView control, should the item array have at least an Id and Title rather than being any.  This might save a lot of trouble down the road.

**Comment by estruyf** [comment]
The idea behind it is that it does not really matter which data you pass through the control. If you do not specify anything, it renders the object and flattens out the property objects.

Making the ID and Title required could limit the usecases for some projects, but it is a good feedback to take into consideration.
