### ISSUE TITLE
fileTypeIcon only displays PDF's in SPFx 1.8.2

### ISSUE THREAD

**Issue by c-eiser13** [SharePoint/sp-dev-fx-controls-react#300]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [     1.13.1    ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Use the path property of fileTypeIcon with the Image type and see document icon image.

#### Observed Behavior
I have an SPFx 1.8.2 web part and I'am using the fileTypeIcon control as below:

![fti](https://user-images.githubusercontent.com/42096464/57722049-498b4700-764b-11e9-85a7-5323f0ef42aa.PNG)

The doc.docUrl contains a path to the different documents, a combination of Office and PDF. The PDF image shows, but none of the Office document types display.  Tested same markup above in SPFx 1.7.1 web part and it works as expected for all document types.

Here is a screenshot of the markup for an item that has a path to a .docx:
![css](https://user-images.githubusercontent.com/42096464/57721862-d8e42a80-764a-11e9-92ce-700045d309cf.PNG)

@AJIXuMuK  assited with a similar icon issue in the reusable property controls and I suspect this may be a similar issue. If any further info is needed, just let me know. Thanks!

#### Steps to Reproduce
Create new 1.8.2 web part and add a fileTypeIcon control with image type and a path to an office document.

**Comment by AJIXuMuK** [comment]
It looks like we have much larger issue with branded icons...
If you look at [official docs](https://developer.microsoft.com/en-us/fabric#/styles/web/office-brand-icons) we should use `getFileTypeIconProps` method to display branded icon.
But it looks like this method doesn't work with version `5.131.0` of `office-ui-fabric-react` that is used in the controls...

@estruyf what do you think?
The only fix for now that I see is to request all png icons directly from Office UI Fabric CDN how it is done for "unknown" file types...

**Comment by estruyf** [comment]
@AJIXuMuK actually we already had a CDN fallback implemented for PDF file. So what I did right now is to make the CDN fallback the default for image icons and added all the supported file types to the CDN fallback.

Before:

![Screenshot 2019-05-17 14 53 16](https://user-images.githubusercontent.com/2900833/57929461-af7a0780-78b3-11e9-95ad-5caf31c0044a.png)

After: 

![Screenshot 2019-05-17 14 53 06](https://user-images.githubusercontent.com/2900833/57929468-b56fe880-78b3-11e9-9f70-228064ef4f6b.png)

This will be included in version `1.13.2`, feel free to test out the beta to see if it fixes it in your scenario. 

Here you can read more information on how you can test out the latest beta version: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by AJIXuMuK** [comment]
Yep, that is exactly what I meant!
Great!

**Comment by c-eiser13** [comment]
Thanks @AJIXuMuK and @estruyf , I've installed the beta and can confirm the images are working correctly.  I came across [this](https://github.com/OfficeDev/office-ui-fabric-react/issues/9090) issue in the OUIF repo where the new branded office icons appear to have a new CDN URL, may be something to look at moving forward if any changes need to be made. Thanks again for the quick turnaround!

**Comment by estruyf** [comment]
This has just been released in the version `1.13.2`. Will create a new issue for the new CDN URL.
