### ISSUE TITLE
SecurityTrimmedControl - No permissions template

### ISSUE THREAD

**Issue by antoniobriones** [SharePoint/sp-dev-fx-controls-react#307]
Hi, this is just a suggestion..

I implemented this control to handle the logic of checking user permissions for me, but then i realized I had to put some message if the user didn't have them, otherwise, the entire section would be empty and the user wouldn't understand what was going on.

Since this control doesn't have any "No permissions template" i finally had to write code to check if the user didn't have permissions and show a placeholder with a message in that case, finally, ended up using my custom code for everything, would be great if it could have this functionlity too.

**Comment by estruyf** [comment]
Thanks! This could be a nice enhancement to the control.

**Comment by oveiyakrish** [comment]
I am sure this post has helped me save many hours of browsing other related posts just to find what I was looking for. Many thanks!
https://www.gangboard.com/full-stack-developer-course?utm_source=backlinks&utm_medium=cmt&utm_campaign=coursepage&utm_term=fullstackdeveloper&utm_content=oveiya

**Comment by sympmarc** [comment]
Above comment looks to be spam. Are there mechanism here to handle?

**Comment by Varuuna** [comment]
I would be willing to create a PR for this issue, but wouldn't mind a bit of advise on how to best implement it. The control was designed to display content when the permissions matched, so what is the best approach when you suddenly want to do the complete opposite?

**Comment by antoniobriones** [comment]
I would modify the control to receive two templates, the default one for "permissions match" and one other, optional, for "not enough permissions".

**Comment by mgwojciech** [comment]
Looked like an easy thing. There is pull request waiting:
https://github.com/SharePoint/sp-dev-fx-controls-react/pull/474/
