### ISSUE TITLE
How do you make the WebPartTitle reactive?

### ISSUE THREAD

**Issue by parithon** [SharePoint/sp-dev-fx-controls-react#31]
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [1.1.1]

#### Expected / Desired Behavior / Question
I'm new to the react world and still learning. That said, with the WebPartTitle component how do we get the same reactive behavior we get OOTB from the @microsoft/sharepoint webpart template's description field?

Below are my edits to the files generated by the @microsoft/sharepoint yeoman template.

##### IHelloWorldProps.ts
```javascript
import { DisplayMode } from '@microsoft/sp-core-library/lib';
export interface IHelloWorldProps {
   title: string;
   description: string;
   displayMode: DisplayMode;
   updateProperty: (value: string) => void;
}
```

##### HelloWorldWebPart.ts (truncated for brevity)
```javascript
export interface IHelloWorldWebPartProps {
   title: string;
   description: string;
}
export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
   render(): void {
      const element: React.ReactElement<IHelloWorldProps> = React.createElement(
         HelloWorld,
         {
            title: this.properties.title,
            description: this.properties.description,
            displayMode: this.displayMode,
            updateProperty: (value: string) => this.properties.title = value
         }
      );
      ReactDom.render(element, this.domElement);
   }
}
```

##### HelloWorld.tsx (truncated for brevity)
```javascript
...
import { WebPartTitle } from '@pnp/spfx-controls-react/lib/WebPartTitle';

export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
   public render(): React.ReactElement<IHelloWorldProps> {
      <div className={ styles.helloWorld }>
         <div className={ styles.container }>
            <div className={ styles.row }>
               <div className={ styles.column }>
                  { /* <span className={ styles.title }>Welcome to SharePoint!</span> */}
                  <WebPartTitle className={ styles.title}
                     title={this.props.title}
                     displayMode={this.props.displayMode}
                     updateProperty={this.props.updateProperty}
                  />...
```

##### HelloWorldWebPart.ts (truncated for brevity)
```javascript
...
 protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
      ...
      groups: [
         {
            groupName: strings.BasicGroupName,
            groupFields: [
               PropertyPaneTextField('title', {
                  label: 'Title Field'
               }),
              PropertyPaneTextField('description', {
                 label: strings.DescriptionFieldLabel
              })
            ]
         }...
```

**Comment by estruyf** [comment]
Hi @parithon,

Yes, that is exactly the way you need to implement it. 

The only thing what you do not have to do is adding the field to the property pane. That is totally up to you if you want to do this.

```
PropertyPaneTextField('title', {
  label: 'Title Field'
})
```

**Comment by parithon** [comment]
Hi @estruyf,

I do have the property pane text field in my code, see the last code example (admittedly I did have the title for the code incorrect labeled, it should have been HelloWorldWebPart.ts instead of HelloWorld.tsx, fixed above).

The problem I'm running into is that when I updated the values on either the WebPartTitle or the PropertyPaneTextField it doesn't updated the values of the other control. Ultimately the webpart's property value is updated, but only after you refresh the page do you see the changes.

Is this a problem with my implementation or a bug on the WebPartTitle component?

**Comment by parithon** [comment]
![2018-01-08_9-07-03](https://user-images.githubusercontent.com/8602418/34682332-7829652c-f453-11e7-8eb6-ed467c7b33ed.gif)

Here is an example animated gif.

**Comment by estruyf** [comment]
This is neither a bug or problem, this is how the control was designed. 

The control is initially created to change the property in the content section. If we want to support both at the same time, there is additional code required on the webpart side.
