### ISSUE TITLE
ListPicker add ability to filter the control in other ways

### ISSUE THREAD

**Issue by araver** [SharePoint/sp-dev-fx-controls-react#319]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.13.1]

#### Expected / Desired Behavior / Question
Ability to filter list using something other than list template

I think it would be nice to have a promise like callback that would allow the developer to filter, or possibly a filter string that could be sent on the "GET" request or both.

**Comment by gitbrent** [comment]
I second this request.

Adding a new property that would allow filtering the list using an OData query (e.g.: `Active_x003f_ eq true`) would greatly benefit this component as returning all items is not always desired.

I'd be willing to provide a PR to add a new `filter` property and any other work required.

**Comment by araver** [comment]
@gitbrent I've created a PR in the property pane controls. I can copy the changes over to this project or if you'd like to, you can duplicate the changes. [PR 189](https://github.com/SharePoint/sp-dev-fx-property-controls/pull/189)

**Comment by estruyf** [comment]
This has now been copied over from the control project and will be available in version `1.14.0`. Please feel free to test out the latest beta to see if it fits your needs. More information about how you can test out a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by gitbrent** [comment]
Thanks @estruyf - this is precisely what I had envisioned.

**Comment by estruyf** [comment]
This is now included within the `1.14.0` release
