### ISSUE TITLE
Question in relation to Saving Multi Taxonomy Values to SP Document

### ISSUE THREAD

**Issue by gbminnock** [SharePoint/sp-dev-fx-controls-react#322]
[X ] Question

#### Version 1.13.2

Please specify what version of the library you are using: [1.13.2         ]

Hi, 
I am successfully using the Taxonomy Control. The taxonomy it references is attached to a column in a document library. I would like to use this control to update a document library item. After some research I am not sure it is possible (P.S. its a multi field). I have tried a few different variations of the method below to transform the terms to something which can be used to update the document library item.
`````typescript
    private normalizeTaxonomy = (value: any[], previousValue: any[]) => {

        let transformedArray = value.map((term: any) => {
            return {
                __metadata: { type: "SP.Taxonomy.TaxonomyFieldValue" },
                Label: term.name,
                TermGuid: term.key,
                WssId: -1
            };
        });

        let normalizedTaxonomy = {
            results: transformedArray
        };
        return normalizedTaxonomy;
    }
``````
I get this error when I try to update the item (I use @pnp/sp and @pnp/odata library for this): 
````bash
FormSubmit.ts:63 Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"A node of type 'StartArray' was read from the JSON reader when trying to read a value of a property; however, a 'PrimitiveValue' or 'StartObject' node was expected."}}}
    at new HttpRequestError (parsers.ts:13)
    at parsers.ts:19
````

Any guidance on how to update the taxonomy column in my doc library would be appreciated. 
Thanks,
Gary

**Comment by wills01** [comment]
Hi, I successfully update multiple taxonomy fields

Note I use IPickerTerms for MultiTaxonomy, and just IPickerTerm for single values

` public async updateMeta(TargetwebUrl: string, terms: IPickerTerms, listName: string, fieldName: string, term: IPickerTerm, field: string,Content:string, item: Item): Promise<any> {
    const data = {};

// Single Value Taxonomy Field

    data[field] = {
      "__metadata": { "type": "SP.Taxonomy.TaxonomyFieldValue" },
      "Label": term.name,
      'TermGuid': this.cleanGuid(term.key),
      'WssId': '-1'
    };

// This looks up ContenttypeID from Content Type Name

    let Targetweb = new Web(TargetwebUrl);
    const list = await Targetweb.lists.getByTitle(listName);
    const fieldname = await list.fields.getByTitle(`${fieldName}_0`).get();

    let cts = await list.contentTypes.get();

// Set ContentTypyeId

    cts.forEach(ct => {
      if(ct.Name == Content){
        data['ContentTypeId'] = ct.StringId;

      };
      

    });


// Set Multi-Taxonomy Field

    let termsString: string = '';
    terms.forEach(term => {
      termsString += `-1;#${term.name}|${this.cleanGuid(term.key)};#`;
    });

    data[fieldname.InternalName] = termsString;

// Update Item

    return item.update(data);

  }`

**Comment by gbminnock** [comment]
Hi @wills01, that works perfectly. I didn't know about the different format for multi valued taxonomy fields and the use of those backing fields "name_0".
Thanks a mill.
Gary

**Comment by ymihir** [comment]
@wills01 in my case I am seeing two hidden note fields for multi value taxonomy field suffix with _0 and _1.  This behavior is not happening all the time but happened in production. Not sure the reason. We are creating SP site with custom site template. Out of 26 sites, for two sites it is giving issue. Somehow we are able to find correct associated hidden field between _0 and _1 and fix SPFx code, but while doing the search, results are not coming. This is really giving pain. Any idea on how we can delete extra hidden column or stop this kind of issue to be happen?
