### ISSUE TITLE
SecurityTrimmedControl  remove the wrapping div element that is being returned

### ISSUE THREAD

**Issue by ckruszynsky** [SharePoint/sp-dev-fx-controls-react#325]
#### Category
[ X ] Enhancement

[ ] Bug

[ ] Question

#### Version 
1.13.2 

#### Expected / Desired Behavior / Question
Please either remove the wrapping div element on the render of the secruityTrimmedControl or provide a prop that either accepts styles or a class. If you are building a Flex grid the wrapping div element will break the layout and rendering of the contained elements.

**Comment by estruyf** [comment]
This is related to React which always requires to return one parent element. In React 16 you have fragments that can solve this issue, but as we are currently working with SPFx 1.3.0, it needed to be implemented as a `div`.

Adding a className property could indeed be a quick solution to solve this. Once we update the project to `1.8.2` or later (new major release), we can change this to work with React fragments.

**Comment by estruyf** [comment]
This has been implemented and can be tested out by installing the latest beta version. More information about installing a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by ckruszynsky** [comment]
Awesome, Thank you Elio!

**Comment by estruyf** [comment]
This is now included within the `1.14.0` release
