### ISSUE TITLE
PropertyFieldDateTimePicker control Issue

### ISSUE THREAD

**Issue by pavan2920** [SharePoint/sp-dev-fx-controls-react#330]
Hi Team, 

We are using **PropertyFieldDateTimePicker** control, when trying to select time unable to get the dropdowns instead getting a plain Text box to enter the time. 

![image](https://user-images.githubusercontent.com/10346150/60582726-ff028d00-9da6-11e9-865c-0b90e397d201.png)

We are looking for the solution exactly as it is below. 
https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyFieldDateTimePicker/

![image](https://user-images.githubusercontent.com/10346150/60582851-35d8a300-9da7-11e9-9dcc-8d9b24e2b64f.png)

Could you please help in understanding or solving the issue. 

Thansk & Regards, 
Pavan.

**Comment by AJIXuMuK** [comment]
Hi @pavan2920 
For React Controls we decided to use Masked Text box instead of dropdowns.
If there is a need we can probably add an option to select between two.

@estruyf what do you think?

**Comment by mahesh087** [comment]
Hi @AJIXuMuK @estruyf 
Having an option to select between two would be great.

Thanks in advance!

**Comment by estruyf** [comment]
We could introduce an option.

**Comment by pavan2920** [comment]
Thank you @AJIXuMuK , @estruyf 

It would be great to have that option.

**Comment by jayeshvg** [comment]
Yes, As a user, I would feel good to select time rather than type it.
It would also be good if we can give intervals, meaning, if we can select minutes in interval of 5m or 15m etc.

Thanks,
JG

**Comment by AJIXuMuK** [comment]
Addressed in #349, currently without intervals.

**Comment by estruyf** [comment]
Closing this issue as version `1.15.0` has just been released.
