### ISSUE TITLE
We need a listPicker  control/

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-fx-controls-react#34]
#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

#### Version
Just like we have in the Property pane controls, but to put in the webpart body, Just a adropdown on lists on the site. Would be really great to be able to have it select only lists based on a specific template, or better yet, lists that have a specific content type.

**Comment by russgove** [comment]
and also the ability to select multiple lists.

**Comment by estruyf** [comment]
This control will be available in v1.3.0. You can test out the beta right now.
