### ISSUE TITLE
DateTimePicker does not respect dateLabel and timeLabel

### ISSUE THREAD

**Issue by robert-lindstrom** [SharePoint/sp-dev-fx-controls-react#346]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question
Setting the dateLabel and timeLabel strings as shown below has no effect on the DateTimePicker component.
```typescript
<DateTimePicker strings={{ dateLabel: 'date lbl', timeLabel: 'time lbl', ...  }} ... />
```
This is expected to update the respective labels of the DateTimePicker component.

#### Observed Behavior
Setting the dateLabel and timeLabel properties has no effect to the component.

#### Steps to Reproduce
See above!

**Comment by estruyf** [comment]
Closing this issue as version `1.15.0` has just been released.
