### ISSUE TITLE
FileTypeIcon with font won't work in Field Customizer

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-fx-controls-react#35]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.1.2 ]

#### Expected / Desired Behavior / Question
FileTypeIcon control is displayed correctly when used in Field Customizer.
#### Observed Behavior
FileTypeIcon is not displayed
#### Steps to Reproduce

- create Field Customizer Project with React Framework
- install and reference `@pnp/spfx-controls-react`
- change the customizer markup to be something like
```
<div className={styles.cell}>
  <FileTypeIcon type={IconType.font} path={'.docx'} />
</div>
```
- nothing is rendered

The reason for that is that default office ui fabric classes with `font-family` definitions are not referenced by the component and it has default inherited `font-family`

**Comment by AJIXuMuK** [comment]
Possible solution is to use `Icon` component from Office UI Fabric instead of `i`

**Comment by estruyf** [comment]
That might be a good idea @AJIXuMuK. Thanks for reporting this.

**Comment by estruyf** [comment]
I just released a new beta version that should fix this issue. Would you be able to test it out? You can install the new bits via: `npm install @pnp/spfx-controls-react@next --save`.

**Comment by AJIXuMuK** [comment]
Hi @estruyf 
Yup now it works!

Awesome job! Thanks!

**Comment by estruyf** [comment]
Thanks for testing! I'll release this to version `1.1.3`
