### ISSUE TITLE
TaxonomyPicker: Save and cancel buttons are not translated

### ISSUE THREAD

**Issue by robert-lindstrom** [SharePoint/sp-dev-fx-controls-react#361]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question
The TaxonomyPicker control opens a panel for selecting terms. At the bottom of this panel are two buttons, Save and Cancel. The labels of these buttons are not translated.
Expect button labels to be translated for supported languages, e.g. German where labels should be 'Speichern' and 'Abbrechen' respectively.

#### Observed Behavior
Labels are always 'Save' and 'Cancel' regardless of browser language

#### Steps to Reproduce
Use TaxonomyPicker with browser language set to another supported language (e.g. German).

**Comment by estruyf** [comment]
Closing this issue as version `1.15.0` has just been released.
