### ISSUE TITLE
PeoplePicker doesn't show mandatory asterisk in label when isRequired={true}

### ISSUE THREAD

**Issue by mfdezvil** [SharePoint/sp-dev-fx-controls-react#371]
#### Category
[ ] Enhancement

[ X] Bug

[ X] Question

#### Version

1.14.0 (latest release)

#### Expected / Desired Behavior / Question
If "isRequired" is set to true in PeoplePicker component, mandatory asterisk should appear in label, as other office-ui-fabric-react components. Doesn't it?

#### Observed Behavior
When I implement a PeoplePicker component and set "isRequired={true}", mandatory asterisk doesn't appear in label. 

#### Steps to Reproduce
Create a PeoplePicker component and a TextField component in a SPFX WebPart with this code: 

`<TextField id="TxtField" label="Text Field" onChange={this.onChangePageTitle} required={true} />
<PeoplePicker
    context={this.props.context}
    titleText="People Picker"
    personSelectionLimit={1}
    groupName={""} 
    isRequired={true}
    selectedItems={this._getPeoplePickerItems} 
    showHiddenInUI={false}
    principalTypes={[PrincipalType.User]}
    resolveDelay={1000} />`

As you can see, "isRequired"/"required" properties are set to true in both components. However, when webpart is rendered, label only shows a mandatory asterisk in TextField. Shouldn't the asterisk show in both components?

**Comment by estruyf** [comment]
Closing this issue as version `1.15.0` has just been released.
