### ISSUE TITLE
Rookie problem - gulp serve not running... 

### ISSUE THREAD

**Issue by mikezimm** [SharePoint/sp-dev-fx-controls-react#395]
#### Category
[x] Question

#### Version
1.15.0

#### Expected / Desired Behavior / Question
Not able to load the web part in local host or SPO workbench.
I think I followed instructions properly but I keep getting gulp serve not running.

#### Steps I followed:
1. forked a copy of the repo
2. opened sp-dev-fx-controls-react folder in vscode
2. npm install
3. npm install @pnp/spfx-controls-react@next --save
4. tried modifying package.json per [this post ](https://stackoverflow.com/questions/52179949/npm-err-refusing-to-install-package-with-name-packagename-under-a-package-also). 
5. gulp serve (also tried --nobrowser)
6. did not get any errors while it was building.
7. got error message below.
8. then also tried updating the package-lock.json file with the same thing.
9. Just to be sure I didn't have a PC issue, I pulled up another project, gulp served it this project loaded and worked just fine.

#### Observed Behavior
When refreshing the workbench on my site, I got this error message:
Your web part will not appear in the toolbox. Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running.

Thanks for any guidance in what I missed!

**Comment by AJIXuMuK** [comment]
Hi @mikezimm 
May it be related to [this one](https://github.com/SharePoint/sp-dev-docs/issues/1002)?

**Comment by mikezimm** [comment]
Hi @AJIXuMuK , Thanks!  That did work!

More specifically to summarize:
I had the dev entry in package.json to be this (last line set NODE....):

```json
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test",
    "dev" : "set NODE_NO_HTTP2=1&& gulp serve"
  },
```

Then to run I had to type
`npm run dev`

All works!  Thanks again for the help!
