### ISSUE TITLE
IFramePanel module not found

### ISSUE THREAD

**Issue by robiharid** [SharePoint/sp-dev-fx-controls-react#397]
I am doing `npm install @pnp/spfx-controls-react/lib/IFramePanel --save --save-exact`

having installed spfx-controls-react --exact it is not showing up

I want to render a pdf in the web part, from the ServerRedirectedEmbedUri property of a document

**Comment by AJIXuMuK** [comment]
Hi @robiharid 
You should install the whole library, not a specific component:
```
npm install @pnp/spfx-controls-react --save --save-exact
```

And then you can import needed component and use it in your code:
```typescript
import { IFramePanel } from '@pnp/spfx-controls-react/lib/IFramePanel';
```

**Comment by robiharid** [comment]
> Hi @robiharid
> You should install the whole library, not a specific component:
> 
> ```
> npm install @pnp/spfx-controls-react --save --save-exact
> ```
> 
> And then you can import needed component and use it in your code:
> 
> ```ts
> import { IFramePanel } from '@pnp/spfx-controls-react/lib/IFramePanel';
> ```

I have installed the library as the documents state. You can see the node module in the @pnp folder and the appropriate error on the import:

![image](https://user-images.githubusercontent.com/16907484/67586105-bfdabc00-f748-11e9-9d2d-03d3fe10788a.png)

**Comment by AJIXuMuK** [comment]
What version of the library do you use?
The current version is 1.15.0.

Could you try to uninstall the module with `npm uninstall @pnp/spfx-controls-react --save` and then install it again?
```
npm install @pnp/spfx-controls-react --save --save-exact
```

I just double-checked and the component is there, in the `lib`.

**Comment by AJIXuMuK** [comment]
Hey @robiharid 
Have you figured out what the issue was?

**Comment by robiharid** [comment]
> Hey @robiharid
> Have you figured out what the issue was?

Yo sorry, I believe I had an older version but specifitying the version on npm i fixed it, thank you!
