### ISSUE TITLE
using controls in ListView Command sets

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-fx-controls-react#408]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

Hi, trying to use the peoplepicker in a listview commandset. it has a webpartcontext as a pareameter but in a listviewcommandset i dont have one. Can we use these controls in a litview command set?

**Comment by AJIXuMuK** [comment]
Hi @russgove!
Currently no. But I will make the change to use custom `IContext` or something instead of web part context. In that case the controls will be available in extensions as well.
