### ISSUE TITLE
Color of WebpartTitle

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-fx-controls-react#41]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.1.3]

#### Observed Behavior
The color of WebpartTitle with a theme dark is not iso with title of default title (see screenshot)

![webpart_title](https://user-images.githubusercontent.com/582733/35394147-3ac8f9a8-01e7-11e8-97e1-d15b727a6461.png)

Thanks!

**Comment by estruyf** [comment]
This seems to be a UI Fabric issue which is overriding the title web part color. Same happens for the group info text underneath the site title.

<img width="334" alt="screenshot 2018-01-26 11 00 15" src="https://user-images.githubusercontent.com/2900833/35432258-2c181924-0288-11e8-940b-16329f7a57be.png">

You could always add your own class to the title and specify the color. The control itself inherits the color from its parent, as this gives control to the developer. If we set the color within the control, it will make things harder to override the color.

**Comment by PooLP** [comment]
Hi Elio,

I have tested with dynamic theme color on title, it's work perfectly by default and with a overridden color ;).

![pull_request](https://user-images.githubusercontent.com/582733/35435556-774aa7ba-028b-11e8-889e-6d631e114724.png)

My fork : https://github.com/PooLP/sp-dev-fx-controls-react/
I make a pull request if you want?

Thanks,
Richard

**Comment by estruyf** [comment]
I included it with the latest `dev` update.

**Comment by estruyf** [comment]
Thanks for opening this issue!

**Comment by PooLP** [comment]
Sharing is caring! it's a good philosophy.
