### ISSUE TITLE
[docs] Link to Charts is broken

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/sp-dev-fx-controls-react#417]
On the public website for documentation, the link to Charts is currently broken, returning a 404 not found:

https://sharepoint.github.io/sp-dev-fx-controls-react/controls/ChartControls

**Comment by AJIXuMuK** [comment]
Hi @jimmywim!
Thank you for reporting this one!
It'll be fixed in the next version.

**Comment by estruyf** [comment]
Version 1.16.0 is out, this includes the fix for this issue.
