### ISSUE TITLE
PeoplePicker errorMessage not showing

### ISSUE THREAD

**Issue by giovanibm** [SharePoint/sp-dev-fx-controls-react#420]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.15.0]

#### Expected / Desired Behavior / Question
See an error message in the component when the property isRequired is true and errorMessage is informed.

#### Observed Behavior
Error message is not showing.

#### Steps to Reproduce
Just try to use this properties, it will not work.

#### Submission Guidelines
I was looking at ../src/controls/peoplepicker/PeoplePickerComponent.tsx and the state is not properly initiate with the props given to the component.

Thanks!

**Comment by Matej4386** [comment]
Agree, i have just test it yesterday, Error message parameter has no effect.

**Comment by giovanibm** [comment]
Actually the error was in another place, a wrong inline test in render method.
PR #430 opened, now we have just to wait :)

**Comment by evdma** [comment]
The error message still not showing
