### ISSUE TITLE
TaxonomyPicker: Possibility to hide deprecated and "Available for Tagging"=false term

### ISSUE THREAD

**Issue by PzYon** [SharePoint/sp-dev-fx-controls-react#421]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version
1.15.0

#### Desired Behavior
I would like to be able to configure the TaxonomyPicker to hide terms that are not selectable by the user anyway, as for example "Available for Taggin"=false and deprecated terms. Please see below print screen. I guess in certain situations it might make sense to show these terms and in certain situations it might not make sense.

#### Observed Behavior
![image](https://user-images.githubusercontent.com/9199378/69875847-5eb18580-12be-11ea-8c0f-b03d5f3c4c43.png)
NYC - "Available for Tagging"=false
BER - Deprecated

**Comment by JonasBjerke89** [comment]
I did a small PR to solve this request: https://github.com/SharePoint/sp-dev-fx-controls-react/pull/437
