### ISSUE TITLE
Slovak localization 

### ISSUE THREAD

**Issue by Matej4386** [SharePoint/sp-dev-fx-controls-react#424]
Category
[x] Enhancement
[ ] Bug
[ ] Question

Please add Slovak localization labels.

**Comment by Matej4386** [comment]
I can help with localization, just let me know how.

**Comment by AJIXuMuK** [comment]
Hi @Matej4386,

It would be great if you could add the localization!

**Comment by Matej4386** [comment]
I am kind of new to this :-) Could you please tell me how, i can download en local file, translate, and send it to where? Or is there any other process?

**Comment by AJIXuMuK** [comment]
@Matej4386,

You need to use the same process as for any other contributions to GitHub repos.
1. Fork the repository
2. Clone forked repo
3. switch to `dev` bracnch
4. create new branch based on `dev` with `git checkout -b <branch-name>`
After that you should go to `src/loc` folder. It contains all the localizations.
Add new file with correct name for Slovak culture and copy-paste content from `en-us.ts`.
Do the translation.
When all that done you can commit and push your changes to the GitHub.

After that you'll be able to go back to this repo and create new Pull Request.
**IMPORTANT: target the PR to DEV branch.**

Let me know if you need more details.

**Comment by Matej4386** [comment]
Hi @AJIXuMuK 
thanks for information. I will try to overcome company restrictions (proxy, internet access, ...) to be able to clone forked repo ...
