### ISSUE TITLE
IFrameDialog "commitPopUp" typo causes popups with classic forms to not close after hitting save

### ISSUE THREAD

**Issue by JRRSG** [SharePoint/sp-dev-fx-controls-react#433]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  1.15.0  ]

#### Expected / Desired Behavior / Question
When using the IFrameDialog control to render classic forms in a popup in SharePoint Online, the dialog popup should close after hitting Save or Cancel.

#### Observed Behavior
After the iframe is rendered containing the classic form, hitting Cancel triggers the event and the popup closes as expected. However, after hitting Save the event is not triggered and the popup remains open and the classic list view is shown.

After searching high and low for why cancel was working and save was not, I noticed that SharePoint uses different casings of "popup" for the commit and the cancel events.

The cancel function used in SharePoint is:
<code>window.frameElement.cancelPopUp</code>

The commit function is:
<code>window.frameElement.commitPopup</code>

<code>commitPopup</code> is typed as <code>commitPopUp</code> in the PnP control

#### Steps to Reproduce
-- Create an SPFx solution that renders a classic form in a popup dialog using the IFrameDialog control
-- Test the solution on a modern page
-- Open a classic form in an iframe popup and test the Cancel and Save events  //only Cancel fires
-- Change "commitPopUp" to "commitPopup" in the PnP IFrameDialog control files and test the SPFx solution again  //both Cancel and Save will fire as expected

This picture shows a snippet from SharePoint's sp.ui.dialog.debug.js file and I've circled the different casings of "popup" used by <code>this.$0_0.cancelPopUp</code> compared to <code>this.$0_0.commitPopup</code>
![Annotation 2019-12-09 104602](https://user-images.githubusercontent.com/28233790/70450348-8d272180-1a71-11ea-800a-364e990c38dc.jpg)

This picture shows the current code used in IFrameDialogContent.tsx
![Annotation 2019-12-09 121031](https://user-images.githubusercontent.com/28233790/70456872-0710d800-1a7d-11ea-91a7-b542138badfe.jpg)

**Comment by AJIXuMuK** [comment]
Thank you @JRRSG for reporting this one!
The fix has been committed and is available in beta version.
Please, feel free to test the version.

**Comment by estruyf** [comment]
Version 1.16.0 is out, this includes the fix for this issue.
