### ISSUE TITLE
Question About React / SPFx ListView

### ISSUE THREAD

**Issue by subhasishmukhopadhyay** [SharePoint/sp-dev-fx-controls-react#438]
#### Category
[ ] Enhancement

[ ] Bug

[ Y ] Question

#### Version

Please specify what version of the library you are using: [   NA      ]

This is a question related to ListView control in react and to display large sets of list items.

https://sharepoint.github.io/sp-dev-fx-controls-react/controls/ListView/

Question : 
If we try to show all list items using getAll() is it loading all data at once or if we scroll down the page then getAll will execute recursively and populate the data partially? Is it good for performance or any other suggestion?

public componentDidMount() {
    sp.setup({
      spfxContext: this.props.context
    });
    sessionStorage.clear();
    sp.web.lists.getByTitle("<list>").items.select("Id,Title,PeoplePickerField/Title").expand("PeoplePickerField").getAll().then((response) => {
      this.setState({
        items: response
      });
    });
  }

**Comment by AJIXuMuK** [comment]
Hi @subhasishmukhopadhyay,
Here is a [documentation](https://pnp.github.io/pnpjs/sp/docs/items/#get-all-items) on this method.

> Using the items collection's getAll method you can get all of the items in a list regardless of the size of the list. Sample usage is shown below. Only the odata operations top, select, and filter are supported. usingCaching and inBatch are ignored - you will need to handle caching the results on your own. This method will write a warning to the Logger and should not frequently be used. Instead the standard paging operations should be used.

So, it will return all the data and render all the data as well.
