### ISSUE TITLE
[RichText] - Problem with edit mode

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-fx-controls-react#445]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

spfx : 1.9.1
sp-dev-fx-controls-react : 1.16
Sharepoint OnLine : Targeted and Standard release
Chrome/Edge : latest version
Windows 10 : latest version

#### Expected / Desired Behavior / Question
The edit mode don't work anymore

#### Observed Behavior
I'm use a richText editor in a WebPart to edit a simple introduction text. in edit mode, the richText do not switch to edit.

The problem started last week, and I didn't do any component-side updates (no update, the webpart was already installed and worked very well). 

I updated to PnP SPFx Control 1.16, but I still have the problem. 

I have tested on Chrome and Edge latest version with same problem.

I have tested with React DevTools. The condition pass a "isEditMode" attribut to true, but the "editing" state of component stay at false. (see screenshot)

![richtext](https://user-images.githubusercontent.com/582733/70922061-bd4c6280-2025-11ea-987c-62ccef1159f7.jpg)

I have tested with simple condition :
`
this.props.displayMode == DisplayMode.Edit
`
And state method, componentDidUpdate ... a lot of test.

Does anyone reproduce the problem?

#### Steps to Reproduce
- Create a WebPart and add richText
- Insert webpart to page (edit mode work on first insert)
- Save the page
- Reload the page
- switch page to edit mode and try the edit of richtext

Thanks

**Comment by AJIXuMuK** [comment]
Hi @PooLP!
I can reproduce that. It looks like SharePoint page lifecycle has been changed.
And the changes showed the error in `RichText` component.

I've committed the fix. 
Could you please install the beta version and check if it works for you.

[How to install beta version](https://sharepoint.github.io/sp-dev-fx-controls-react/beta/)

**Comment by PooLP** [comment]
After test, it's ok for me.
Thanks.

PS :
I tried to resolve this bug myself.
I created a fork of the repos (dev branch), installed dependencies by npm -i
But, after lanched the gulp serve command, the debug didn't worked on my SharePoint environnement, i have error message like if serve do not run, i have this error :

> An error occurred while loading the debug script. Make sure the server is running and that the URL for the "debugManifestsFile" parameter is appropriate.
> 
> Error: Script error for: https://localhost:4321/temp/manifests.js http://requirejs.org/docs/errors.html#scripterror

Do we need to do something more (run on docker an env with 1.3.0 spfx version of generator, specific version of VSC ...) ?

**Comment by AJIXuMuK** [comment]
Glad to hear it's resolved.

For the local development, you can do one of 3:
1. set no http2 as mentioned [here](https://github.com/sharepoint/sp-dev-docs/issues/1002)
2. Use [nvm](https://github.com/nvm-sh/nvm) and install node v6
3. use docker

I use nvm :)

**Comment by PooLP** [comment]
Thanks, I will do that! ^^
I close the issue.
