### ISSUE TITLE
listPicker always return "test" when multiple allowed

### ISSUE THREAD

**Issue by s1nce** [SharePoint/sp-dev-fx-controls-react#458]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.16.0 ]

#### Expected / Desired Behavior / Question
List picker should return the list of chosen or empty array or null when multiple is allowed

#### Observed Behavior
"test is always included as the first element from return even no item is chosen

#### Steps to Reproduce
It only happens when **multiSelect** is enabled
```
<ListPicker
                    context={this.props.context}
                    multiSelect={true}
                    label='Select your list(s)'
                    includeHidden={false}
                    onSelectionChanged={(selected) => console.log(selected)} />
```

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @s1nce!
Thanks to @mgwojciech it has been fixed and will be available in the next version.
You can also test it in current beta version.
