### ISSUE TITLE
ListView selected Items not updated with column sort

### ISSUE THREAD

**Issue by gbminnock** [SharePoint/sp-dev-fx-controls-react#46]
#### Category

[x ] Bug

#### Version

Please specify what version of the library you are using: [   1.2.1      ]

#### Expected 
I expect that selected records would update when sorting invoked

#### Observed Behavior
The records selected do not move, they stay in the same position. i.e. records 1,2,3 selected and then user invokes sorting then the selection does not stay with the same records

#### Steps to Reproduce
Use List View with multiple selection and sorting enabled for each column. select 3 records. Sort on a column. 

Thanks!

**Comment by estruyf** [comment]
Thanks for reporting this, we will check out what is happening.

**Comment by estruyf** [comment]
I did a bug fix, would you be able to test it out? Try it out via installing this: `npm install @pnp/spfx-controls-react@next`.

**Comment by gbminnock** [comment]
@estruyf,
yes tested and works fine now thanks! 
I may have stumbled across an anomaly when clicking sort on the same column multiple times. I have attached  a screenshot which shows the sorting gives slightly different results when clicked multiple times, is this expected give the data I have? If not I can open a new defect if required. Please see attached screenshots. 
Gary

![image](https://user-images.githubusercontent.com/2708345/36301380-7f3016be-12fc-11e8-933a-27795e34231e.png)

![image](https://user-images.githubusercontent.com/2708345/36301386-8643c8e2-12fc-11e8-93c8-77cdd7f8e7fa.png)

**Comment by estruyf** [comment]
That seems to happen because both values are the same. Does it happen when clicking on the same title, or when for example sort on the title and after that on Genre? Because in that case, it makes sense as it depends on the current item order.

**Comment by gbminnock** [comment]
Happens when sorting on the same column "Genre" multiple times. I guess since both records have the same value there's an element of randomness there. Anyway thanks for solving the original issue.
