### ISSUE TITLE
Placeholder for Taxonomy Picker

### ISSUE THREAD

**Issue by rabwill** [SharePoint/sp-dev-fx-controls-react#464]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version
 7.82.1

A placeholder property for TaxonomyPicker , see image below

![image](https://user-images.githubusercontent.com/20379311/72581325-b2d5ff00-392a-11ea-8a2d-971189880fba.png)

Thanks!
Rabia

**Comment by rabwill** [comment]
Happy to pick this up , I am thinking of adding a new property  **placeHolder**  and passing it as inputProps (native input property) of the JSX element TermBasePicker.

**Comment by AJIXuMuK** [comment]
Hi @rabwill,
Thank you for the idea! It was much easier to just implement than getting back and forth on GitHub :)
So, the `placeholder` property should be available in beta and in the next drop.

I've also included you as a contributor for the version as this is completely your idea and you provided the possible implementation description.

**Comment by rabwill** [comment]
Thanks so much Alex ! You're a legend  😊

**Comment by RicoNL** [comment]
Would it be possible to implement the placeholder also on the PeoplePicker?

**Comment by AJIXuMuK** [comment]
Thank you @rabwill for kind words :)

@RicoNL - I'm thinking of expanding it to all pickers we have.

**Comment by AJIXuMuK** [comment]
Done for `ListItemPicker` and `PeoplePicker`.
For the `ListPicker` I deprecated `placeHolder` and added `placeholder` so all the pickers have the same property.
All the changes are available in beta and will be included in the next drop.
