### ISSUE TITLE
ListView filtering doesn't work for fields with custom rendering defined

### ISSUE THREAD

**Issue by benjblack** [SharePoint/sp-dev-fx-controls-react#465]
#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    1.16     ]

#### Expected / Desired Behavior / Question
Typing anything into the filter box should filter rows based on what is displayed to the user, regardless of what the underlying datatype/value is.

#### Observed Behavior
If a customer render() handler is defined for a field, the value typed into the search box doesn't work for that field.

#### Steps to Reproduce
Define a renderer for the field.  Example code below. In this case, searching/filtering won't work for any DateTime or Date fields.  

public render(): React.ReactElement<ISpListViewProps> {
...
          if(listField.TypeAsString == "DateTime"){
            fld.render = (item, index, column):any => {
              const dt = moment(self.state.listItems[index][column.fieldName]);
              return dt.format('MM/DD/YYYY, h:mm A');
            };
          }else if(listField.TypeAsString == "Date"){
            fld.render = (item, index, column):any => {
              const dt = moment(self.state.listItems[index][column.fieldName]);
              return dt.format('l');
            };
...

**Comment by AJIXuMuK** [comment]
Hi @benjblack,
Thank you for reporting this!
Currently filtering works based on the values of fields, not displayed text.
Custom rendering can render even icon instead of any text. And we don't have control on that.
As a possible solution I could propose adding additional property to `IViewField` something like `containsValue(item, filterValue): boolean` that you can override. And we'll use it in the filter operation.

Will it work for you?

**Comment by jaxnz** [comment]
> Hi @benjblack,
> Thank you for reporting this!
> Currently filtering works based on the values of fields, not displayed text.
> Custom rendering can render even icon instead of any text. And we don't have control on that.
> As a possible solution I could propose adding additional property to `IViewField` something like `containsValue(item, filterValue): boolean` that you can override. And we'll use it in the filter operation.
> 
> Will it work for you?

Any update on this? I am using a render method with two objects, but would really like to filter either those objects or the text displayed
