### ISSUE TITLE
ListView iconFieldName image for unknown application

### ISSUE THREAD

**Issue by gbminnock** [SharePoint/sp-dev-fx-controls-react#47]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Version

Please specify what version of the library you are using: [    1.2.1     ]

#### Question
How do I add an application image for an application which is not included OOTB?

#### Observed Behavior
Unable to use image for my application while using a ListView

#### Steps to Reproduce
set iconFieldName=link to file

Thanks!

**Comment by estruyf** [comment]
That's currently not supported as we make use of the Office UI Fabric icon set. If the application is unknown for Office UI Fabric, it falls back to the generic icon.

**Comment by gbminnock** [comment]
Ok thanks!
