### ISSUE TITLE
Question: new components - folders list and folder picker

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-fx-controls-react#470]
#### Category
[x] Enhancement

[ ] Bug

[x] Question

#### Expected / Desired Behavior / Question
Hi, I recently created a reusable folder picker control that I should be able to port to this repository. Should I submit a PR?

Sample picker control:

![image](https://user-images.githubusercontent.com/19577724/73005044-2df25600-3e00-11ea-8586-6f8c67ed5a7b.png)

Clicking the icon to select a folder on the right side of the control opens a panel to select a folder
![image](https://user-images.githubusercontent.com/19577724/73005302-a3f6bd00-3e00-11ea-89eb-b03144e559b0.png)

When an item is selected, it renders a link to that folder

![image](https://user-images.githubusercontent.com/19577724/73006013-d228cc80-3e01-11ea-80e2-f2a169c4a6b2.png)

The inner control (folders list + filter + folder creation) is also reusable as it works independently from the picker and side panel, 

![image](https://user-images.githubusercontent.com/19577724/73005142-59754080-3e00-11ea-8b1a-9c8e536c12d5.png)

Sample code for folder picker:

```
<FolderPicker webPartContext={this.props.webPartContext}
rootFolder={this.props.selectedFolder}
defaultFolder={this.state.defaultFormFolder}
onSelect={this._onDefaultFolderSelect.bind(this)}
label='Upload folder'
canCreateFolders={true}>
</FolderPicker>
```

Sample code for folders list
```
<FoldersList
webPartContext={this.props.webPartContext}
rootFolder={this.props.rootFolder}
defaultFolder={this.state.selectedFolder}
onSelect={this._onFolderSelect}
canCreateFolders={this.props.canCreateFolders}
/>
```

**Comment by AJIXuMuK** [comment]
Hi @joelfmrodrigues!
Feel free to add it!
If it is needed once, it could be needed for others!

**Comment by joelfmrodrigues** [comment]
@AJIXuMuK took me long to be able to find some time for this, but the PR for the first control is now submitted.
This is a folder explorer which I have now used in a couple of projects and is also used by the folder picker control mentioned above.
I will try to submit PR for the other control before the end of the week 😊

**Comment by AJIXuMuK** [comment]
Awesome job @joelfmrodrigues!

I have merged your PR!

Thank you for the contribution!
