### ISSUE TITLE
Is it possible to reuse the Article Page Header web part used in Sharepoint Modern Sites?

### ISSUE THREAD

**Issue by sanrzdz** [SharePoint/sp-dev-fx-controls-react#479]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

Hi. I would like to know if there is any way to reuse the page header web part that is set by default in the Article Pages in Sharepoint Communication site:

![image](https://user-images.githubusercontent.com/4968845/74260166-f71daa80-4cf0-11ea-8d37-3fd9540ef292.png)

I need to do some customizations (render more data) and would like to reuse some functionality of the web part instead of develop everything from scratch.

I tried to find it across differents SP repos without any luck. 

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @sanrzdz!
Unfortunately, it's not even a web part, it's a part of page layout.
Even if we create custom component for that, you won't be able to replace out-of-the-box one.

**Comment by sanrzdz** [comment]
Hi @AJIXuMuK,

I know it is not defined as a web part but, as it is possible to change the page layout programmatically to avoid render the out-of-the-box header, having the possibility to re use would be great.
