### ISSUE TITLE
FilePicker keeps the URL's hash dirty

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-fx-controls-react#488]
#### Category
[x] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    1.16.0    ]

#### Expected / Desired Behavior / Question
When using the file picker and switching to different content providers - the control changes the hash in the page's URL.
When a file is selected and the picker is closed - I would expect the hash to return to empty or what it was before, so it won't break other control's functionality.

Either make the hash empty when the control is done, or bring back what was there before. Best yet - don't change the hash at all! (this this is a picker and not a control that is always open, IMHO it shouldn't change the hash of the entire page at all...)

#### Observed Behavior
After the picker was used, the hash will stay "#onedrive" or "#globe"

#### Steps to Reproduce
Use the picker and select a different content category, select a file and close the picker.

**Comment by AJIXuMuK** [comment]
Hi @shaipetel,

I have added new property to `FilePicker` props:
```typescript
/**
   * Specifies if last active tab will be stored after the Upload panel has been closed.
   * Note: the value of selected tab is stored in the queryString hash.
   * @default true
   */
  storeLastActiveTab?: boolean;
```

If you set it to `false` the hash will not be modified.
By default the behavior remains as is.

You can test it in beta version and it will be available in the next drop.

**Comment by shaipetel** [comment]
Perfect. Thanks!

**Comment by shaipetel** [comment]
So, I just got 1.17.0 installed and the property storeLastActiveTab does not exist on the file picker.

What am I doing wrong?

**Comment by shaipetel** [comment]
Spoke too soon. Took a few minutes and a rebuild and now it shows up and works. thanks!
