### ISSUE TITLE
FilePicker bingAPIKey not working

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-fx-controls-react#489]
#### Category
[x] Bug

#### Version

Please specify what version of the library you are using: [   1.16.0      ]

#### Expected / Desired Behavior / Question
Specified bingAPIKey, expected to be able to go to search search for images

#### Observed Behavior
After specifying the API key I get an error message in the console when trying to search in the picker.
it makes a call to bingapis.com and gives a 401 error, followed by this error:
[BingFilesService.executeSearch]: Err='Something went wrong when executing search query. Status='undefined''

I cannot seem to find a place to set my bing API endpoint. I created an API key using my azure tenant and got a key + endpoint, but this control only expects a key.

#### Steps to Reproduce
Use this control, set the bing api key from one generated using azure.
Set only the key, as there is no way to set the endpoint.
try to use the search in the picker.

**Comment by AJIXuMuK** [comment]
Hi @shaipetel!
Thanks for reporting this one.
I've done the fix. It is available in beta version and will be included in the next drop
