### ISSUE TITLE
ListView and IViewField documentation

### ISSUE THREAD

**Issue by frankok** [SharePoint/sp-dev-fx-controls-react#493]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [   1.16.0      ]

Hi,
Is there any extended documentation somewhere on how to set up the IViewField collection to be used for displaying the items in the ListView control?
I'm having a hard time figuring out what possibilities there are, and this in combination of selecting and filtering the items using the REST call. 

For displaying a Hyperlink column, I've tried the following:

{
      name: 'SiteUrl',
      displayName: "Site",
      sorting: true,
      isResizable: true,
      maxWidth: 100,
      render: (item: any) => {
        return <a href={item['SiteUrl']}>{item['Title']}</a>;
      }
    },

But this just displays the Title, and no link.

Also, do you have any guidelines for fetching and displaying Metadata columns? Right now, they're blank in the ListView: 
  {
      name: "Business_x0020_UNit",
      displayName: "Business Unit",
      isResizable: true,
      sorting: true
    },

![image](https://user-images.githubusercontent.com/20436301/75524282-e1f18d00-5a0d-11ea-950a-fcf7ea058206.png)

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @frankok,
Unfortunately, we don't have any extended documentation on `IViewField`.
The rendering of this or that column strongly depends on how the value is returned by SharePoint.
I would recommend try to combine `ListView` with [`FieldRendererHelper`](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/fields/FieldRendererHelper/) and Field Controls available in the library.
