### ISSUE TITLE
DateTimePicker behaviors

### ISSUE THREAD

**Issue by Leomaradan** [SharePoint/sp-dev-fx-controls-react#495]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.16.0]

#### Observed Behavior
The DateTimePicker component does not have a homogeneous behavior with the onChange event. When entering a invalid value, the onChange event is triggered sometime with latest valid value, and sometime it return Invalid Date

#### Steps to Reproduce
I created a repository with a small webpart containing only the DateTimePicker and a onChange Handler
https://github.com/bpa-solutions/demo-webpart-datepicker

Steps:

0. Place the WebPart on the page. picker date is empty, the picker hour is set to "12 AM" and the picker minute is set to "00"
1. Click on the Date picker, and select the current date (03 March 2020) => **the onChange event return "Tue, 03 Mar 2020 11:00:00 GMT"**
2. Change the Hour to "08 AM" => **the onChange event return "Tue, 03 Mar 2020 07:00:00 GMT"**
3. Remove the Hour => **the onChange event return the last valid value ("Tue, 03 Mar 2020 07:00:00 GMT")**
4. Set the Hour to "13 AM" => **the onChange return "Tue, 03 Mar 2020 00:00:00 GMT", and a label "Incorrect hour value" is displayed under the Hour picker**
5. Set to a correct date (03 Mar 2020 21:00:00 GMT) and then remove the Minute part => **the onChange return an invalid date, and the Date picker is now set to Invalid Date too!**
6. Click on the Date picker, and select any date => **the new date is not set, because the Minute is empty**

The component is stuck after the step 6. The user has to first set a new Minute value, and after that he can select a date again.

#### Desired Behavior
The Picker must either only return the last valid date, or not triggering the onChange.
The Picker must not be stuck. Changing the Minute must not change the Date to _Invalid Date_.
If a invalid minute is set, a error message must be displayed.

**Comment by AJIXuMuK** [comment]
Fixed in the next drop
