### ISSUE TITLE
Taxonomy Picker showing deprecated terms, how to hide them

### ISSUE THREAD

**Issue by mukeshhope** [SharePoint/sp-dev-fx-controls-react#506]
HI Team,

I am using Taxonomy picker control and it also shows deprecated terms.
although they are disabled but i want to hide them. is it possible to hide them ?

**Comment by AJIXuMuK** [comment]
Hi @mukeshhope!
This functionality will be available in the next version (1.17.0).
You can also install beta version and check in there.

PR with the changes: [https://github.com/SharePoint/sp-dev-fx-controls-react/pull/437](https://github.com/SharePoint/sp-dev-fx-controls-react/pull/437)

**Comment by mukeshhope** [comment]
HI Alex,
Thank you so much. beta version is just working fine.
do you have any idea of when it should be expected to be released

**Comment by AJIXuMuK** [comment]
Hi @mukeshhope,
It should be released in the next few weeks.

**Comment by mukeshhope** [comment]
Thanks Alex.. I will close this issue
