### ISSUE TITLE
Version 1.17.0 - Cannot find module '@pnp/spfx-controls-react/lib/ComboBoxListItemPicker - 

### ISSUE THREAD

**Issue by siddharth-vaghasia** [SharePoint/sp-dev-fx-controls-react#509]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version - 

Please specify what version of the library you are using: [    1.17.0     ]

"@pnp/spfx-controls-react": "^1.17.0-beta.b815cd4",

Screenshot of package.json file

![image](https://user-images.githubusercontent.com/9557557/77390878-47425f00-6dbd-11ea-95d9-685ddf1af2ec.png)

 #### Observed Behavior
I was trying new version 1.17.0 and while importing ComboBoxListItemPicker we are getting below error. 

![image](https://user-images.githubusercontent.com/9557557/77390610-89b76c00-6dbc-11ea-8394-cc315e7236fa.png)

Used below command to install the latest package

`npm i @pnp/spfx-controls-react@next`

Please note that  IconPicker is working fine and import is also successful. 

Further Analysis from my side, not sure if below will help.

1. Inside node_module/@pnp/spfx-controls-react, we don;t see comboboxlistitempicker folder.

![image](https://user-images.githubusercontent.com/9557557/77390773-f7fc2e80-6dbc-11ea-9d23-d6b58ce78dbb.png)

2. As per the source repo code, Combobox list item picker is supposed to be inside listitemPicker folder which is also missing in the that folder also(refer above screenshot).

![image](https://user-images.githubusercontent.com/9557557/77390832-1c580b00-6dbd-11ea-9755-d5b6e2487e98.png)

Thanks!
Siddharth

**Comment by joelfmrodrigues** [comment]
@siddharth-vaghasia I believe there is an issue with the package as it no longer seems to be listed on npm. 
I had the same problem when updating a sample project from using the beta version to v1.17.
Elio is already aware :)

**Comment by joelfmrodrigues** [comment]
@siddharth-vaghasia check the version installed on your package.json, in my case was using 1.16
If so, uninstall and run the install command again to install 1.17 as Elio has now resolved the publishing issue.
This worked for me

**Comment by PrasadKasireddy** [comment]
@joelfmrodrigues  -this issue is still appearing I installed the latest v1.17 however, I can not find the @pnp/spfx-controls-react/lib/ComboBoxListItemPicker'


![image](https://user-images.githubusercontent.com/11626905/77423920-47ab1c00-6df6-11ea-8a40-3d8055808016.png)

![image](https://user-images.githubusercontent.com/11626905/77424224-be481980-6df6-11ea-8b85-2b1e739f14fd.png)

**Comment by siddharth-vaghasia** [comment]
@joelfmrodrigues .....yes...working now...thanks..!!! though we have to update the documentation at https://github.com/SharePoint/sp-dev-fx-controls-react/edit/master/docs/documentation/docs/controls/ComboBoxListItemPicker.md ...
Import statement should be as follow

import { ComboBoxListItemPicker } from '@pnp/spfx-controls-react/lib/listItemPicker';

**Comment by siddharth-vaghasia** [comment]
> @joelfmrodrigues -this issue is still appearing I installed the latest v1.17 however, I can not find the @pnp/spfx-controls-react/lib/ComboBoxListItemPicker'
> 
> ![image](https://user-images.githubusercontent.com/11626905/77423920-47ab1c00-6df6-11ea-8a40-3d8055808016.png)
> 
> ![image](https://user-images.githubusercontent.com/11626905/77424224-be481980-6df6-11ea-8b85-2b1e739f14fd.png)

use below import statement

import { ComboBoxListItemPicker } from '@pnp/spfx-controls-react/lib/listItemPicker';

**Comment by AJIXuMuK** [comment]
Thank you @siddharth-vaghasia for reporting and fixing!
The fix will be available in the next version.

**Comment by siddharth-vaghasia** [comment]
thanks..closing issue now...
