### ISSUE TITLE
Need some more implementation documentation with regards to FieldUserRenderer control

### ISSUE THREAD

**Issue by trillian74** [SharePoint/sp-dev-fx-controls-react#51]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [     current    ]

Question
I can't seem to figure out quite how i use this control, could you provide a link to an actual demo sample or maybe elaborate more in the documentation?
Keep up the great work, i appreciate it daily:)

**Comment by estruyf** [comment]
@AJIXuMuK is this something you can do?

@trillian74 what would you like to see being added to the documentation?

**Comment by AJIXuMuK** [comment]
@estruyf, Yep, will be my pleasure.
@trillian74 please, let us know what additional information you'd like to see.

Currently we have few scenarios described on how to use Field Controls including `FieldUserRenderer`.

- if you go to [Getting started](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/fields/main/) page for Field controls you'll see example on how to use `FieldRendererHelper` that will automatically detect needed type of Field control based on Field Type.
- on `FieldUserRenderer control` page you can find the code that you can use to embed `FieldUserRenderer` into your Field Customizer.

Let us know if you need something more.

**Comment by trillian74** [comment]
thanx
I'm wondering most upon the  `users={event.fieldValue} `  Normally i just have the siteuserid or login for the user i want to render. I see that it wants IPrincipal. I've tried building one, but no cigar on this control.

**Comment by trillian74** [comment]
Let say how do i complete this within a listviewfields
` private viewFields: Array<IViewField> = [
        {
            name: "Id", displayName: "Id"
        },
        {
            name: "AuthorId", displayName: "Author", render: ((d: any) => {
                sp.web.getUserById(d.AuthorId).get().then((user) => {....`

i want to render out author as a user control with card?

**Comment by trillian74** [comment]
I have this ListView control (in a webpart) that has sp user column, which of course only have Ids like AuthorId etc.... In the ListView i want to render the column using the FieldUserRenderer control. 

Is this possible using the ListView and Array<IViewField> with override render?

**Comment by AJIXuMuK** [comment]
@trillian74 
I didn't play around with `ListView` control and its `render` override.
From `FieldUserRenderer` point of you - yes, you can do that if you provide the `IPrincipal` info as I described above.

**Comment by estruyf** [comment]
@trillian74 can this issue be closed?

**Comment by trillian74** [comment]
Thanx
