### ISSUE TITLE
Relationship with Fabric UI React

### ISSUE THREAD

**Issue by hittoday** [SharePoint/sp-dev-fx-controls-react#532]
do these controls have any relationship or dependency with the Office UI Fabric React  controls?

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components

What known issues are there using both libraries? in the same project

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @hittoday!
Yes, the library is based on `office-ui-fabric-react@5.131.0`

**Comment by hittoday** [comment]
Thankyou for the prompt reply! That clears that up!
Downside upgrade paths 
Upside community support tailored to spfx


Sent from Yahoo Mail for iPhone


On Tuesday, April 7, 2020, 6:31 pm, Alex Terentiev <notifications@github.com> wrote:




Hello @hittoday!
Yes, the library is based on office-ui-fabric-react@5.131.0
