### ISSUE TITLE
User cannot be found in FieldUserRenderer

### ISSUE THREAD

**Issue by a1exymoroz** [SharePoint/sp-dev-fx-controls-react#541]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version

Please specify what version of the library you are using: [ 1.17.0 ]

#### Question
I use `FieldUserRenderer` with `this.context`
```javascript
 <FieldUserRenderer users={users} context={this.context} />
```
And i have request error `User cannot be found.` for `'...absoluteUrl.../_api/web/getUserById(14)`.

But if i send request via `import { Web } from '@pnp/sp';`, everything is worked
```javascript
const web = Web('...absoluteUrl.../sites/...');
web.getUserById(14).get()
```
I think problem in `this.context.pageContext.site.absoluteUrl`. How can  i change absolute url?

Site where I tested: `...absoluteUrl.../_layouts/15/workbench.aspx`
Thanks!

**Comment by a1exymoroz** [comment]
I deployed package on sharepoint and `FieldUserRenderer` is working, but  how I can use `FieldUserRenderer` on workbranch?

**Comment by AJIXuMuK** [comment]
Hi @a1exymoroz!
`FieldUserRenderer` as many other components is not intended to work in local workbench.
You can still test it in hosted workbench using url `your-web-absolute-url/_layouts/15/workbench.aspx`.
In that case you don't need to deploy anything to SharePoint but you'll have the context of the web.

**Comment by a1exymoroz** [comment]
Yes, It was my fault.
I needed to add to url my subsite `../sites/.../_layouts/15/workbench.aspx`.
Thank you!
