### ISSUE TITLE
PNP SPFx FilePicker Control - Uploading to SharePoint not working

### ISSUE THREAD

**Issue by siddheshwarkohale** [SharePoint/sp-dev-fx-controls-react#543]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

["@pnp/spfx-controls-react": "1.17.0" ]

#### Expected / Desired Behavior / Question
While uploading, once we add selected image, it should upload to SharePoint library.

#### Observed Behavior
We are using FilePicker control in SPFx web part for Images uploading, We thought that it would work as like default. But this control is not capable to upload files to SharePoint. After uploading it should go to SharePoint library but currently nothing is happening.

#### Steps to Reproduce
Create a sample test SPFx project
Add PnP SPfx File Picker react control
Try to upload images 

We did exactly like this article - https://www.c-sharpcorner.com/article/how-to-use-filepicker-control-of-pnp-in-spfx-webpart/

https://sharepoint.github.io/sp-dev-fx-controls-react/controls/FilePicker/

Thanks!
Sid

**Comment by gobigfoot** [comment]
The control doesn't actually upload the item because the location has not been identified.

```js
// I'm filling out an array of files from the picker
const attachments: IFilePickerResult[] = [];


// Map over the results to build out the object
const values = await Promise.all(
attachments.map(a => a.downloadFileContent()
    .then(r => {
      return { name: a.fileName, content: r };
    })
  )
);

// Attach to list item
const list = sp.web.lists.getByTitle("ListTitle");
const itemId = 1;
const attachmentAddResult = await list.items
  .getById(itemId)
  .attachmentFiles
  .addMultiple(values);

// I'm sure there is other code for adding to a document library, but this is my use case
```

**Comment by siddheshwarkohale** [comment]
Thanks for the reply.

Actually I have written custom code to upload selected local file and could able to upload to specified document library as well. 
<FilePicker
                buttonLabel="Select File"
                context={this.props.context}
                accepts={[".gif", ".jpg", ".jpeg", ".bmp", ".dib", ".tif", ".tiff", ".ico", ".png", ".jxr", ".svg"]}
                onChanged={(selectedFile: IFilePickerResult) => {
                  alert("On changed called..");
                  return event;
                }}
                onSave={(filePickerResult: IFilePickerResult) => {
                  // write code to save file to SharePoint doc library
                  alert("On save called..");
                  this.onUpdate(filePickerResult);
                  return event;
                }}
                 />

But main issue is that "this.onUpdate(filePickerResult) this custom method gets called on File picker's every action like Upload, Site, Recent, one drive. I want to restrict uploading method for only Upload action.

On changed method not firing at all.

Thank you.
BR.
Sid

**Comment by gobigfoot** [comment]
I see in my code update and save have the same actions that stores the selections in state and I have a separate submit button on the form itself.

**Comment by AJIXuMuK** [comment]
Hi @siddheshwarkohale!
The component itself just allows you to select the file. It doesn't upload it anywhere. You should handle upload by yourself.
