### ISSUE TITLE
ListView reset selected items

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-fx-controls-react#55]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [@pnp/spfx-controls-react@1.2.4]

#### Question
Hello, how I can reset selected items in ListView?
For example in cases when delete an item from list, UI still keeps selecting another item I guess with the same index as was the last.

Thanks!

**Comment by estruyf** [comment]
Will get fixed in the next release. Thanks for reporting this.

**Comment by estruyf** [comment]
The fix is now available in the beta version. Feel free to test it out by installing it as follows: `npm i @pnp/spfx-controls-react@next --save`

**Comment by estruyf** [comment]
Closing the issue as this is now available with the latest release. Feel free to open the issue again if it still occurs in v1.2.5.
