### ISSUE TITLE
Wiki contributions

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-fx-controls-react#6]
#### Category
[ ] Enhancement

[ ] Bug

[ X ] Question

#### Expected / Desired Behavior / Question
Hi,
Can you open the wiki for contributions please

Thanks
Joel

Thanks!

**Comment by estruyf** [comment]
Unfortunately, GitHub wikis are not open for contributions. We looking to publish the documentation somewhere else in the future, but for now, we stay in the wiki. 

If you want, you can share the info in the issue for what you want to change and I will update it.

**Comment by joelfmrodrigues** [comment]
Hi @estruyf 

Just a little thing:
[https://github.com/SharePoint/sp-dev-fx-controls-react/wiki/ListView](https://github.com/SharePoint/sp-dev-fx-controls-react/wiki/ListView)
Step 3 has a reference to a different control

**Comment by estruyf** [comment]
It has been updated
