### ISSUE TITLE
ListView selected items error

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-fx-controls-react#71]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

[   1.2.5     ]

#### Expected / Desired Behavior / Question
Documentation example contains the 'selection' property, although this is currently an option property and omitting it causes a JavaScript error. 
Property should not be optional **or** code should check if this._selection is not undefined.

Happy to submit a PR if given direction on the preferred approach (check if this._selection is not undefined?)

#### Observed Behavior
"TypeError: Cannot read property 'setItems' of undefined" 
ListView.tsx, line 63

#### Steps to Reproduce
Add a ListView control without 'selection' property.

**Comment by estruyf** [comment]
@joelfmrodrigues this was already reported in #67 and #65 and fixed in v1.3.0. You can test it out by installing the latest beta.

**Comment by joelfmrodrigues** [comment]
That's great, thanks
Searched on the list of open issues for similar items, but not closed ones :|
Closing...
