### ISSUE TITLE
[Question] - How did you manage to use add and delete buttons dynamically ?

### ISSUE THREAD

**Issue by aplantard** [SharePoint/sp-dev-fx-controls-react#79]
Hello,

I'm currently working on my own webpart ans I would like to use buttons that allow me to dynamically add or delete some fields in the property pane.
I saw that you've managed to do it in your "PropertyFieldsSPListQuery"
I would like to know and understand how did you manage to do that ?

Thank you very much in advance

Best regards

**Comment by estruyf** [comment]
Hi @aplantard, which buttons do you mean? Can you attach a screenshot.

You are pointing to a `PropertyField` control. The code for all these controls can be found in another repository: https://github.com/SharePoint/sp-dev-fx-property-controls/

**Comment by estruyf** [comment]
Going to close this issue. Feel free to reopen it if needed.
