### ISSUE TITLE
Why do you include Application Insights by default ?

### ISSUE THREAD

**Issue by Tinathnath** [SharePoint/sp-dev-fx-controls-react#81]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [1.2.4]

Hello team !

We developped a SPFx webpart for one of our customers. Sometimes the component fails to load. This customer uses a third party product on his SharePoint tenant that uses AppInsights. Our component and this product sometines have conflicts because of that.

I was surprised because we do not use AppInisghts, but I found that you do. Can you explain me why you need this and what informations do you track please ?

Thanks

**Comment by estruyf** [comment]
Hi @Tinathnath, 

Can you explain more about the issues you are facing / errors which occur while loading the component?

We indeed have application insights in place to track the usage of the controls. This way we know which versions of controls are in use, and which ones are used the most. We filter out all unnecessary data. So only component events are sent, no other usage.

If you want, you can check out the filter we have in place here: https://github.com/SharePoint/sp-dev-fx-controls-react/blob/master/src/common/appInsights/index.ts

**Comment by Tinathnath** [comment]
Hi @estruyf 
Here is a screenshot from the error we had.
Thanks for the explanation and the filter. I guess some of our customers wouldn't be happy if they discover a third party library reads their data whithout notice :)
![bug legendre wp yt](https://user-images.githubusercontent.com/3273299/41144178-4f32d426-6afc-11e8-8f89-410d9f0e7d54.PNG)

**Comment by estruyf** [comment]
Would you be able to test out the latest version of the controls? 
Can you try to reinstall all dependencies again?
Which control are you using?

**Comment by Tinathnath** [comment]
We're using the Placeholder in this project
I can't reinstall the dependencies for now, I don't have access to my customer's tenant anymore for the moment :/

**Comment by estruyf** [comment]
@Tinathnath just to let you know we are going to change the whole telemetry. Apparently, Application Insights doesn't fully support multi-key / multi-account yet. So we are changing it so that other solutions like yours can leverage Application Insights without any issues.

**Comment by Tinathnath** [comment]
@estruyf Ok, thanks for letting me know :)

**Comment by estruyf** [comment]
@Tinathnath just wanted to let you know that in the latest release we removed Application Insights from the package. We now use our own tracking module and shared the code of our projects here to have full transparency of how and what gets tracked, which is basically only the controls and versions that are used.

`@pnp/telemetry-js` dependency: https://github.com/pnp/telemetry-js
Our telemetry proxy: https://github.com/pnp/telemetry-proxy-node

This change would allow you to make use of Application Insights in your own projects without any conflicts from us anymore.

Feel free to test it out in the latest beta. More information about testing a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
Closing this issue as it is released in `v1.6.0`.

**Comment by Tinathnath** [comment]
Thanks for sharing these news Elio !
