### ISSUE TITLE
FieldUserRenderer uses email prop for GetPropertiesFor

### ISSUE THREAD

**Issue by phettz** [SharePoint/sp-dev-fx-controls-react#84]
Category
[ ] Enhancement
[x] Bug
[ ] Question

Version
Please specify what version of the library you are using: [1.4.0]

Expected / Desired Behavior / Question
The `FieldUserRenderer` uses the email property in `_requestUserProfile `for `GetPropertiesFor`. Now that works in most cases, but I have encountered some customer where email and account name is not the same. Then I have to send in the account name as email to get it to work.

https://github.com/SharePoint/sp-dev-fx-controls-react/blob/05d6045173360be4712b712abb8c65e455c269a8/src/controls/fields/fieldUserRenderer/FieldUserRenderer.tsx#L249

**Comment by estruyf** [comment]
@phettz thank you for reporting this.

@AJIXuMuK can you pick this one?

**Comment by AJIXuMuK** [comment]
Hi @estruyf,
Yup, I'll be looking into it.

@phettz could you please provide a bit more details? Is that external user or some non standard way of AD sync? I want to reproduce it first if possible.

**Comment by phettz** [comment]
@AJIXuMuK to be fair, its probably not much you can do at the moment when I'm thinking about it, since the IFieldCustomizerCellEventParameters for Person fields only returns email, id, picture, sip and title props. It is users from AD, I have no idea why they have done it like that, probably have some reasons for it. 

I don't know, maybe add another property for  `<FieldUserRenderer users={event.fieldValue} context={this.context} useUserId={true} ...` or somehting and then to another rest query to get the account name before calling the `GetPropertiesFor`
