### ISSUE TITLE
ListView grouping and selection

### ISSUE THREAD

**Issue by phettz** [SharePoint/sp-dev-fx-controls-react#86]
Category
[ ] Enhancement
[ ] Bug
[x] Question

Version
Please specify what version of the library you are using: [1.4.0]

Question

When I have `selectionMode` set to `SelectionMode.single` and click left of the arrow that is used to expand the grouping it selects all the items inside the grouping. Is it possible to turn off this selection when selection mode is single?

**Comment by estruyf** [comment]
This was an issue in the Office UI `DetailsList` component and the current version we use of it. This got now fixed in the latest version.
