### ISSUE TITLE
Disabled property for PeoplePicker

### ISSUE THREAD

**Issue by Octavie** [SharePoint/sp-dev-fx-controls-react#88]
Hi Elio,
Just implemented your cool stuff and working all fine. Though, I would like to see the property Disabled implemented on the PeoplePicker control as it also exists on the original one.

#### Category
[X ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.5.0   ]

**Comment by Octavie** [comment]
If you like I'll try to PR this one... :)

**Comment by estruyf** [comment]
PRs are always highly appreciated @Octavie 👍

**Comment by estruyf** [comment]
Closing this issue as it is released in `v1.6.0`.
