### ISSUE TITLE
PeoplePicker property selectedItems not implemented?

### ISSUE THREAD

**Issue by phettz** [SharePoint/sp-dev-fx-controls-react#90]
#### Category
[ ] Enhancement

[ x] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [   1.5      ]

#### Expected / Desired Behavior / Question

Just tested the new PeoplePicker, and there is a property for:  

> Method to check value of People Picker text

https://github.com/SharePoint/sp-dev-fx-controls-react/blob/23af35a5a35e4fe37951f65d961419c435290788/src/controls/peoplepicker/IPeoplePicker.ts#L40

But it does not look like its in use, or did I miss something?

**Comment by Octavie** [comment]
Hi,
You are right. This was not implemented correctly. I needed it as well today :)
@estruyf I committed a change for this bug as well.

Cheers,
Octavie

**Comment by estruyf** [comment]
Closing this issue as it is released in `v1.6.0`.
