### ISSUE TITLE
people picker control doesn't search using contains

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-controls-react#93]
People picker is searching using starting with like query .Can we change this ?

**Comment by estruyf** [comment]
What would be the wanted behavior in your case?

**Comment by harshdamaniahd** [comment]
For eg if I have to search for a person named :  "Henry Ford".So searching should be possible when i type "Ford" or "enry"

**Comment by AsishP** [comment]
@harshdamaniahd, This is doable and was a quick one actually. Have implemented the change. Will check the with @estruyf where the dev chain is and will push the change.

**Comment by AsishP** [comment]
@estruyf, have submitted the PR.

**Comment by harshdamaniahd** [comment]
@AsishP  and @estruyf  Thank you very much for the effort.

**Comment by estruyf** [comment]
This will be released with version 1.7.0
