### ISSUE TITLE
In People Picker , can we change default behavior to get only users 

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-controls-react#94]
Currently if i make groupName as empty
```
<PeoplePicker
    context={this.props.context}
    titleText="People Picker"
    personSelectionLimit={3}
    groupName={''} // Leave this blank in case you want to filter from all users
    showtooltip={true}
    isRequired={true}
    disabled={true}
    selectedItems={this._getPeoplePickerItems} />
```
**I can still see office 365 groups**
![image](https://user-images.githubusercontent.com/11780473/42686230-de81eea6-86b2-11e8-99ed-e88dbd968b4a.png)

**Comment by AsishP** [comment]
@harshdamaniahd , I suppose this is happening because Office 365 groups have email address and are considered users in the groups created. Might have to check how we can filter unified groups based on attribute. This might take some time.

**Comment by harshdamaniahd** [comment]
@AsishP  ok no issues.
I will wait.

**Comment by estruyf** [comment]
In version `1.8.0` you will be able to specify the `PrincipleType` which you want to retrieve: user, SharePoint group, security group, ... (multiple are possible).

Check the last line:

```
<PeoplePicker
            context={this.props.context}
            titleText="People Picker"
            personSelectionLimit={5}
            // groupName={"Team Site Owners"}
            showtooltip={true}
            isRequired={true}
            defaultSelectedUsers={["tenantUser@domain.onmicrosoft.com", "test@user.com"]}
            selectedItems={this._getPeoplePickerItems}
            principleTypes={[PrincipalType.User]} />
```

Feel free to test out the latest beta. More information about beta testing can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
Closing the issue as version `1.8.0` has just been released.
