### ISSUE TITLE
People Picker Control, find user based on email address

### ISSUE THREAD

**Issue by Arknev** [SharePoint/sp-dev-fx-controls-react#95]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  1.6.0  ]

#### Expected / Desired Behavior / Question
The People Picker doesn't seem to allow for search on email address. In some cases we have an email address without the user's name. Allowing for email search is a feature that is currently available in the classic PeoplePicker and the business is expecting the functionality.

Thanks!

**Comment by AsishP** [comment]
@Arknev, it is implemented and will release a PR soon.

**Comment by AsishP** [comment]
@estruyf, have submitted the PR

**Comment by estruyf** [comment]
This will be in the version 1.7.0 release. Thanks @AsishP.
