### ISSUE TITLE
Column Filter for Listview control

### ISSUE THREAD

**Issue by shrikantmane** [SharePoint/sp-dev-fx-controls-react#99]
#### Category
Enhancement

#### Version
1.5.1

#### Description

I am looking for column filtering option for ListView control. Is this feature planned for future releases?

**Comment by estruyf** [comment]
Thanks @shrikantmane for the suggestion. This would indeed be a good enhancement to the control.

**Comment by estruyf** [comment]
@shrikantmane this will be available with the `1.11.0` release of the new React Controls. You can already test it out in the latest beta. More information about installing the latest beta can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
This has been released with the latest `1.11.0` version. Feel free to test it out, and you can reopen the issue if it still occurs.
